### ISSUE TITLE
[psyir] Add support for dependency analysis with structures (derived types)

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1028]
#363 is adding support for Fortran derived types to the PSyIR. However, it's already a big piece of work so the support for dependency analysis has been postponed to this issue.

**Comment by arporter** [comment]
I suspect this is going to be easiest to address as part of #845.

**Comment by hiker** [comment]
@arporter I have started to support symbols for the dependency analysis, and while this initially worked great, I didn't realise that this of course does not work for derived types, since they are a PSyIR node (while symbols are ... symbols). And I am not sure if we should mix them (though we could of course) - eg. we need to be able to sort them (admittedly mostly for debugging - print all variables alphabetically) - for now I added a ``__lt__`` method to ``Symbol``.

So the question is - what should I use as 'key' (atm the variable name) in the dependency analysis? I see some obvious solutions:
1. in case of a derived type ``a%b...``, we use the symbol ``a`` to capture the access, and add a ``member_accessed`` (or ``psyir_node``) method, which would give us the rest. So an access like ``a%b(i,j)`` would be listed as access to ``a``, with index ``[i, j]``, and member one of ``a%b(i,j)``, ``a%b``, or ``%b``  - not sure which one is possible and would be best? Problem: it would be kind of hard to find all access to "a%b" (you would have to loop over all accesses to ``a``, then use the member access an analyse it further).
2. We change the key to be a PSyIR node. So ``a=b`` would be using a ``Reference`` for ``a`` (and ``b``) instead of a symbol etc, and we could then use the corresponding PSyIR class to reference ``a%b``. The huge problem with this: as far as I can tell if we have say several assignment to a scalar variable ``a``, each one is an instance of Reference - the references would be different, so instead of seeing one variable with several assignments, we would get several variables (with the same name, same symbol, but different psyir-instances).
3. Maybe keep on using strings as key ("a%b"), and add a method to get symbol and/or psyir node?
4. Maybe use a tuple of symbols? ``a%b%c`` would be stored as ``(a,b,c)`` - each a symbol. But then, there is no symbol ``b`` or ``c`` - we might be able to handle this by adding a symbol table to the ``VariableAccessInfo`` object ... but that smells so hacky 👿  

It might depend a bit on what we need to handle. If we only think of accesses like ``a%b%c(i,j)`` ... then using a string or tuple for ``a%b%c`` is fine - but the main problem will be things like: ``a%b(i,j)%c`` :cry: Is there maybe a statement anywhere that declares this as **unsupported** ?? Even worse: ``a%b(i)%c(j)%d`` :cry:

We might need some brainstorming. Does anyone have some examples of derived type accesses we need to support? I can only think of ``a%b%c(i,j)`` as realistic example. I think arrays of structs (``a%b(i,j)%c``) are out of fashion. But I have the feeling I am trying to cheat here :)

**Comment by arporter** [comment]
In answer to your last point, I think we have to be prepared to support any valid Fortran. My experience so far is that as soon as you leave a hole you very quickly find a code that sits in it :-( NEMOVAR makes *very* extensive use of deeply-nested derived types.
I was imagining (obviously without having done any coding) that we would use the `Symbol`s as the keys. However, I too hadn't thought about derived types and, as you say, they really throw a spanner in the works.
I suppose the things we're worried about are the memory locations of all accesses and I have to admit, the simplest way I can think of doing that is just to keep the Fortran string describing the access as the key (your option 3.). However, @sergisiso may have some ideas.

**Comment by hiker** [comment]
Here some notes about a more general approach, before I forget this:

Assumptions: no equivalence (or unions), and no pointers. If there are pointers, I don't think we can safely assume anything.

We are considering accesses of the form: ``a(ia,ja)%b(ib,jb)%c(ic,jc)``. Any part of this can be empty (e.g. ``a%b(i)%c``, ``a``, ``a(i,j)`` etc.)

We call the tuple ``(a,b,c, ...)`` the **signature** of the access. Two signatures ``(a1, a2, a3, ..., ak)`` and ``(b1, b2, b3, ..., bl)`` have a **common complete prefix** if there is a ``n`` so that ``ai==bi`` for ``i=1, ..., n`` and ``n==k or n==l``. This includes that the signatures are identical.

1. It two accesses do not have a common complete prefix, the accesses are independent of each other (without even considering any indices). Example: ``a%b%c`` and ``a%d%e``.

2. Otherwise, the two accesses must be of the form ``(a1, a2, ..., an)`` and ``(a1, a2, ..., an, b1, b2, ...)``. (Typically I would expect that the two signatures are actually identical). Now collect the indices used in accessing ``(a1, ..., an)`` into two lists. The lists must have the same length (since the structure parts a1, ..., an are the same, so the number of indices must be the same). E.g.:
``a(i,j)%b%c(k,l,m)`` would give ``[i,j,k,l,m]``.
In this list discard all elements that are identical on the same position, e.g.: ``[i,j,k]`` and ``[i,x,k+1]`` would get the ``i`` removed and then it is reduced to: ``[j,k]`` and ``[x,k+1]``

    From these list various deducions can be done:
    - If these reduced lists are empty, the same element is accessed (loops can be fused)
    - If we can show that at least one position X with a different value is in both lists, the accesses do not overlap (``[i+4,j]`` and ``[i*i+1, j+1]`` - we might not be able to show this for ``i+4`` and ``i*i+1``, but we know this for ``j`` and ``j+1``).  E.g. a loop that writes (or reads+writes) to the above indices, cannot be parallelised along the ``j`` dimension (nor the ``i``, unless we can symbolically deduce that the ``i``s are never the same).
    - By looking at which variable(s) are used in each element of the lists, and then at the element-wise difference of the two lists
  (e.g.: ``[i+1, j]`` and `[i,j]`` --> ``[1, 0]`` we can make deductions about accessing the same element in different iterations of a 'i'.

So, from the variable usage point of view we should therefore use the signature ( = tuple of string ... or could even be as a single combined string with a separator like % ...``(a,b,c)`` would be ``a%b%c``as key, we just have to be careful then that e.g. ``a%b`` and ``a%bb`` do not have a common complete prefix, which a simple string search would return).

We need to be able to quickly find variable with the same common complete prefix though, but then again, the list of variables will not be that big, and we could use some helper structure to store all prefixes or so. Each access could then have the original expression (either PSyIR or Symbol ... I think) as additional attribute. Plus for each dimension in the signature we store the indices used (None if it's not an array). Again, each entry there could be PSyIR or Symbol(?).

Still some details to sort out, but I hope the concept of handling derived types so far is sound.

**Comment by rupertford** [comment]
Regarding the lists of indices, what would happen in the following case `a(i)%b` and `a%b(i)`?

**Comment by arporter** [comment]
That sounds good to me @hiker. I think I'd favour a tuple (or even a new class if it warrants it) for the signature. It would be good to generalise away from having "%" as separator as obviously that's a Fortran thing. I can imagine the constructor for a signature taking e.g. a `StructureReference` as argument. Alternatively, can we do anything by overloading the comparison operators for `StructureReference` and `ArrayOfStructuresReference`?

**Comment by hiker** [comment]
> Regarding the lists of indices, what would happen in the following case `a(i)%b` and `a%b(i)`?
> 
> It could be stored as ... `[[i],[]]` and `[[],[i]]`?

Well, assuming that this is legal Fortran (so ``a%b(i)`` is the array expression ``a(:)%b(i)``), you would get ``[:,i]`` and ``[i,:]`` (or the lists of lists that you mention ... flattening the list might make simplification etc easier, since we don't need to recursion).  If we analyse a loop over ``i``, it would be noticed that these accesses would potentially overlap - loop variable in different parts. Kind of the same as ``a(i,j)`` and ``a(j,i)``.

**Comment by hiker** [comment]
> That sounds good to me @hiker. I think I'd favour a tuple (or even a new class if it warrants it) for the signature. It would be good to generalise away from having "%" as separator as obviously that's a Fortran thing.

Well, that would be internal only (and we could use |, or any character not used otherwise) - but I think tuples (or a separate class) would be better.

> I can imagine the constructor for a signature taking e.g. a `StructureReference` as argument. Alternatively, can we do anything by overloading the comparison operators for `StructureReference` and `ArrayOfStructuresReference`?

I need to look closely at these classes :)  I am not keen on overloading operators, imho that makes code difficult to understand. 

I'll likely see what tests we need to check e.g. loop fusion or parallelisation, so I can get an idea of what/how we access the signatures etc. That should give us a better idea about the implementation,

**Comment by arporter** [comment]
I agree about operator overloading - I keep thinking I'll find a good use for it one day so just thought I'd mention it :-)

**Comment by arporter** [comment]
It looks as though this one can be closed @hiker?
