### ISSUE TITLE
Nodes can currently be inadvertently in multiple places of the tree

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1136]
There is a mistake in `examples/psyir/create.py`

We have code like the following (which looks nice) ...

```
zero = Literal("0.0", REAL_TYPE)
assign1 = Assignment.create(tmp1, zero)
assign2 = Assignment.create(tmp2, zero)
```

However, the problem is that `zero` is a single instance so it will be a child of both assignments and its parent will be the second assignment (as that is the last one updating the parent). Therefore `zero` is a child of `assign1` but its parent is `assign2`.
 
We could have a test in all create methods which check that the parent's of any nodes being passed in have `parent==None`  which would stop this from happening, but this does not help stop the code looking more messy.
 
The original code is nice and compact. It looks much worse having to create multiple instances of the same thing (e.g. zero_1, zero_2). So are there any solutions which look similar to the original (broken) approach? We could support a `copy()` method for a `Node`. We could replicate a node within a create method by default (or if it already has a parent) - which would need a copy() in any case.

**Comment by sergisiso** [comment]
I think these are 2 separate issues:

1. parent checking
> We could have a test in all create methods which check that the parent's of any nodes being passed in have parent==None which would stop this from happening

This would help in this case but there are several ways to assign children (addchild, list operations, ..) and this is a problem in all of them:
```
zero = Literal("0.0", REAL_TYPE)
assign1.addchild(zero)
assign2.children.append(zero)
```
I think the solution should be more fundamental, all children assignments end up now using the Node::ChildrenList class for validation, I think this class could also manage the parent link transparently (remove parent setter - which also simplifies user code).
I thought about this before but I didn't know if the second assignment had to:
- fail: the children already has a parent
- steal: remove children from assing1

For what you say seems that failing is the sane option, and stealing can be done explicitly anyway:
```
zero = assign1.children.pop()
assign2 = Assignment.children.append(zero)
```
(This can still fail if the assing1 children_validation is now invalid due to the children displacement, e.g. when stealing children 0 of an IfBlock. Hopefully it already does.)

2. Copying
> We could support a copy() method for a Node. We could replicate a node within a create method by default (or if it already has a parent)

I don't like the 'replicate if it already has a parent'-option because:
```
zero = Literal("0.0", REAL_TYPE)
assign1 = Assignment.create(tmp1, zero)
assign2 = Assignment.create(tmp2, zero)
zero.value= "1.0"
```
would just update assing1 and is not clear from the syntax.

But I am OK with the other 2 options:
- create always makes a copy (in this case the syntax will be the same as the previous example but zero.value will not update any of the assingments)
- `assign2 = Assignment.create(tmp2, zero.copy())`. I think I slightly prefer this option because it is clearer that posterior modifications to zero will not affect the assing2 version. And again this will be coherent with the other operations (`assign2.children.append(zero.copy())`) which need to have the python list semantics (and Python semantics in general)

**Comment by arporter** [comment]
I like Sergi's suggestion of adding a `.copy()` and checking that `parent` is not set within the `create` method.

**Comment by sergisiso** [comment]
This should be fixed now
