### ISSUE TITLE
Generalise process_nemo.py script.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1142]
As noted here https://github.com/stfc/PSyclone/pull/1109#discussion_r583761364, it would be useful if `process_nemo.py` (in examples/nemo/scripts) was generalised so as to support batch processing of any application. The only NEMO-specific code in that script is the list of files to exclude and as @rupertford suggested, this could be read from a configuration file.

**Comment by sergisiso** [comment]
As discussed this morning, the files we exclude are due to errors in some of the processing steps. To create a more robust/generic script we could recover from this errors by putting the original source in case a file fails to be processed.

The problem we currently have is that some of the errors are silent. We need to prevent silent errors to generalize process_nemo.py

**Comment by sergisiso** [comment]
I am implementing this as part of #2600
