### ISSUE TITLE
Add support for expression comparison

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1202]
At the moment the check for fields being the same or different when creating an argument list in the algorithm layer is based on strings. Therefore `field(i+1)` and field(1+i)` would be considered to be different. It would be better to use the `math_equal()` method but we need to wait until the code to create the argument list for the PSy-layer has been updated to use the new approach so both can be updated at the same time.

**Comment by rupertford** [comment]
This is part of the ongoing #753 - so closing this issue.

**Comment by hiker** [comment]
(I noticed that this ticket is closed, but since I don't see symbolic maths mentioned in #753): I do indeed intend to add support for symbolic comparison as part of my work on the dependency analysis, see #1075 (my idea is to make sympy optional, since it comes with a large number of dependencies, numpy etc).
