### ISSUE TITLE
Add support for Functions to fparser2 frontend

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1240]
Currently, Fortran functions are put into CodeBlocks by the fparser2 frontend. However, we need them represented as `Routine` nodes in order to process NEMO source.

**Comment by rupertford** [comment]
Presumably it would make sense for the return_type to be changed to a return_symbol (or even list of symbols for future languages)?

**Comment by arporter** [comment]
As @rupertford suggests, I think option 1. is least complicated. What does @sergisiso think?

**Comment by sergisiso** [comment]
Agreed, option 1 (storing the return symbol) seems the easier option since is more akin to how Fortran does it.

Probably in the future we can think of giving a datatype to the RoutineSymbol as it is like the signature to use the Routine externally (without its implementation), but for the moment I think we just need it internally to parse and generate again the function, so the return_symbol should be enough.
