### ISSUE TITLE
Declaration ordering error

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1347]
If a new Fortran type is declared and then used to define a variable then the ordering of these declarations is not honoured when translating to PSyIR and then back to Fortran. This means that the resulting code will not compile. For example ...
``` 
        type :: field_type
          real :: data(10)
        end type
        type(field_type) :: a
```
is output as ...
```
        type(field_type) :: a
        type :: field_type
          real :: data(10)
        end type
```
which causes a compile error (at least for gfortran).

**Comment by arporter** [comment]
This is a problem when processing NEMO's obs_fbm.f90. In that case the declaration in question ends up as an UnknownFortranType because it uses a KIND intrinsic to assign an initial value to the kind paremeter:

      INTEGER, PARAMETER :: fbdp = SELECTED_REAL_KIND(12, 307)

**Comment by arporter** [comment]
Martin Schrieber has also reported:

The problematic code seems to be related to

    INTEGER,PARAMETER     :: rlg=8
    REAL(kind=rlg), INTENT(OUT)  :: datetosec

since the backend of PSyIR first prints all IN, then all OUT fields.

**Comment by arporter** [comment]
I have the basics working, however my check for dependencies does not yet include any symbols used to define the precision of a symbol. (Note that my previous comment on `obs_fbm.f90` in NEMO is also already fixed because we now support having a CodeBlock on the RHS of a declaration. However, it wouldn't work if that CodeBlock itself contained a reference to another parameter.)

**Comment by arporter** [comment]
Can now include two files in NEMO processing that we previously had to exclude (obs_fbm.f90 and par_kind.f90). Resulting code builds fine.
