### ISSUE TITLE
[LFRic] Support for user-defined kernels that operate on DoFs

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#1351]
Originally we had preliminary support for user-defined kernels that operate on DoFs. However, it produced incorrect code and we removed it until the need arises.

There are several LFRic PSyKAl-lite routines that could be removed with this support, hence this issue. Furthermore, it seems that we need to differentiate between `operates_on = DOF` and `operates_on = DOF_COLUMN`.

**Comment by arporter** [comment]
Following on from our chat in the telco this morning, it sounds as though the random-number initialisation functionality needed for PSyAD should also be a dof-wise kernel. In fact, for the simplest case it could just be a built-in? I guess it depends on what Ben's existing kernel code already does?

**Comment by oakleybrunt** [comment]
Rules for proposed builtin:

#### Required parameters to pass to kernel
1. a field
2. unique dofs (for field size)
3. dof currently being operated on (`df`)
-> don't need dof_map since we are operating on every dof in the same manner via a simple loop

#### Allowed metadata types and access
1. field (READ, WRITE, READWRITE)
2.  scalar (READ only)
</br>

If DoFs are a required parameter for the builtin but `dof` is already a keyword reserved for builtins, do we need another user-defined keyword for this type of kernel?

**Comment by arporter** [comment]
#2556 only added the documentation, not the implementation.

**Comment by TeranIvy** [comment]
Completed via #2711 and #2712.

**Comment by sergisiso** [comment]
Reopening, the changelog only says "towards" and there are remaining TODOs in the code mentioning this issue. But I will mention in the title that they only have to do with the stub generation.
