### ISSUE TITLE
[PSyIR] Add option to Visitor to disable deep copy of PSyIR tree

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1587]
Currently the Visitor base class always takes a deep copy of the tree it has been passed. This is so that any changes that must be made do not affect the original tree (e.g. for Fortran, we have to flatten all symbol tables inside a routine into a single one). However, this can get very costly if a visitor is being used to compare fragments of a tree (as is done in the SymPy visitor). The current workaround is to use the `_visit()` method of the visitor directly. This issue will formalise support for this by allowing the deep-copy behaviour to be disabled when a Visitor object is created.

**Comment by sergisiso** [comment]
I am hitting the slow visitor behavior again in some Nemo error messages that we report (so LazyString doesn't help).

I am thinking a solution would be to create a DebugVisitor that would be like Fortran but disable the deepcopy and lowering with the class attribute (so it won't be fully Fortran). Higer-level concepts that would normally fail in other visitors could arrive to a generic Node visitor that prints them as e.g. "\<HaloExchangeNode\>" 

And then do a `node.debug_string()` that internally calls it (in order to avoid importing the writer all over the place which usually have a cyclic dependency with most nodes).

The skip deepcopy can also be applied to the SymPyVisitor

@arporter @rupertford @hiker what do you think?

**Comment by arporter** [comment]
That sounds like a good solution to me Sergi. I worry that `Node` has a lot of methods already but possibly that's because of poor design on my and Rupert's part :-)

**Comment by sergisiso** [comment]
>  I worry that Node has a lot of methods

Most of them are fine imo. Is part of having a Normalized Heterogenous AST design, that we have all this normalized API that should work regardless of the Node type, and this is a good thing. So the generic version of every operation should be in Node. (there is a bit of leakage of DSL concepts, but I wouldn't worry about this yet)

**Comment by hiker** [comment]
Sounds like a good idea (including SymPY)

**Comment by arporter** [comment]
The associated PR was merged so closing this.
