### ISSUE TITLE
[PSyIR] Extend UnknownType to have an UnknownArrayType?

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1589]
Currently UnknownType (really UnknownFortranType since that's the language we are coming from) is a 'black box' that hides everything to do with a declaration. The only exception to this is the visibility of the declared symbol since we require that in
order to generate correct code. In a similar way, we *could* extract the shape of any array declaration so that we would then have an Unknown(Fortran)ArrayType. This would help when manipulating code containing symbols of an unsupported type (such as complex). However, we could also argue that if you're having to manipulate code containing unsupported types then perhaps PSyclone should support that type.

(This has arisen as Simon is using PSyclone to transform the NEMO routine that uses complex arithmetic when performing the global sum.)

**Comment by arporter** [comment]
This is also an issue with `InlineTrans` - we need to know whether or not every reference in a routine being inlined is some sort of array access.

**Comment by sergisiso** [comment]
I am more inclined to support missing features, specially complex since its just an instrinsic type, otherwise we are just reimplementing everything on top of UnknownTypes.
e.g. for croco I added support for a separate parameter statement
```
real :: a
parameter (a = 3.4)
```
which now psyclone parses and creates an equivalent:
` real :: a = 3.4 `
This works for every type but UnknownFortranType. e.g. for a complex it will fail.

I am also changing my view on supporting SAVE, since with the new StaticInterface (name not decided) and updates on the dependency analysis we can now better understand its dependency implications. So I am happy to start supporting it.

My preference would be to keep UnknownType as something the tells PSyclone that it should touch it as we don't know the implications/safety of doing so.

**Comment by sergisiso** [comment]
@rupertford is proposing an alternative approach in #2171 where we still have the UnknownType, but it has a method to get the type that it would be if we ignored the unknown parts of the declaration.

This method still requires the transformation to check if it is an UnknownType and then use the partial type as the datatype for the validation/transformation, but I don't mind the explicitness because if it is valid to do this could be context/transformation dependent.
