### ISSUE TITLE
[NVHPC SDK] Transformations with assumed size character dummy arguments

### ISSUE THREAD

**Issue by nmnobre** [stfc/PSyclone#1596]
The NVIDIA HPC SDK Fortran compiler produces an Internal Compiler Error (ICE) when sizing assumed size character dummy arguments:

`NVFORTRAN-S-0000-Internal compiler error. size_of: attempt to size assumed size character       0`

This has also been reported [elsewhere](https://forums.developer.nvidia.com/t/ice-size-of-attempt-to-get-size-of-assumed-size-character/135706).

At the moment, it seems we might have no choice but to either ignore the code snippets where this happens or to workaround the issue by generating appropriate code. I suggest creating an explicit size local variable for each assumed size character dummy argument.

Problematic minimal working example:
```
subroutine ice(assumed_size_char)
  character(len = *), intent(in) :: assumed_size_char

  !$acc kernels
  if (assumed_size_char == 'literal') continue
  !$acc end kernels
end
```

Suggested solution:
```
subroutine ice(assumed_size_char)
  character(len = *), intent(in) :: assumed_size_char
  character(len = len(assumed_size_char)) :: explicit_size_char

  explicit_size_char = assumed_size_char

  !$acc kernels
  if (explicit_size_char == 'literal') continue
  !$acc end kernels
end
```

**Comment by nmnobre** [comment]
Thanks to @rupertford for pointing out I wasn't copying the data over to the new explicit variable. The previously suggested solution avoided the compiler error but was breaking the program semantics.

**Comment by nmnobre** [comment]
The script can appropriately (until someone finds a bug of course) deal with both input and output assumed size character dummy arguments but has currently no support for optional dummy arguments. The script should also be rewritten to use [stfc/fparser](https://github.com/stfc/fparser), my bad.

**Comment by sergisiso** [comment]
> The reason it doesn't is that (for reasons that I can't remember), it doesn't exclude such an IF if the conditional is a BinaryOperation. I need to extend the checks to look for character Literals.

@arporter The issue with this that this will have false positives as it looks for the if_scalar pattern but the issue is only for assumed length character arrays. And that the solution prevents the code using this array to be on the GPU, while @nmnobre proposal would still allow the statement to be in the GPU and won't break kernels at this statement.

Also the original proposal is similar to what Seth proposed for the compiler bug, so now that the bug has resurfaced again, I would give the "assumed_size_to_fix_size_characters" transformation a go.

**Comment by nmnobre** [comment]
@sergisiso I think I'd rather focus in finishing what @arporter started in [1596_exclude_char_literals](https://github.com/stfc/PSyclone/compare/1596_exclude_char_literals). Although a proper transformation would perhaps be more elegant, it achieves nothing in this particular case, I don't think... UNLESS you are thinking beyond NEMO! 🤓

In `dom_vvl_interpol()`, which is the only case that matters (since in the other, `dom_vvl_rst()`, we don't enclose any such character variable in a kernels region),  we are dealing with a sequence of mutually exclusive conditionals, so enclosing the body of each conditional statement is the exact same as enclosing the whole sequence in terms of kernel launches. Keeping the variable on the GPU gives us nothing either given the control flow in this code.

**Comment by sergisiso** [comment]
Yeah ok, I guess it is a quicker first step to fix the CI nvfortran 23.9 problem, but the problem with fixing an issue with file/routine name exclusions is that at some point another branch of NEMO or model that uses psylcone will do the same and trip with the same issue.

**Comment by arporter** [comment]
I take your point about false positives Sergi but hopefully they will be rare - if we check for expressions involving character variables that should get us most of the way there.

**Comment by sergisiso** [comment]
@arporter Maybe we should prioritise this one the next few weeks before we got nemo5 users trying psyclone.

**Comment by arporter** [comment]
> @arporter Maybe we should prioritise this one the next few weeks before we got nemo5 users trying psyclone.

Yes, I'll take a look at where I was up to.

**Comment by arporter** [comment]
I see my branch was purely updating the `acc_kernels_trans.py` and `process_nemo.py` scripts. However, since we must have the declaration for an assumed-size character array (as it has to be a subroutine argument I think) presumably we can do better and put the check in the transformation itself? Is that what you were thinking @sergisiso?

**Comment by arporter** [comment]
The assumed-size character strings cause the compiler to fail while character-string manipulation is (I think) rejected by the compiler in OpenACC regions. Certainly any character intrinsic operations fail but we should be OK with those now because we know they can't be put on the GPU. Actually, I've just checked and it seems that `ACCKernelsTrans` doesn't do any checking for intrinsic calls :-(
