### ISSUE TITLE
Paralelisable indirect access loops 

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1661]
In NEMO (ldfslp.90, trabbc.f90, tradf_iso.f90, ...) there are some loops with indirect accesses, e.g.:
```
DO jj = 1, jpjm1
  DO ji = 1, jpim1
    zgru(ji, jj, mbku(ji, jj)) = gru(ji, jj)
    zgrv(ji, jj, mbkv(ji, jj)) = grv(ji, jj)
  END DO
END DO

do jj = 2, jpjm1, 1
  do ji = 2, jpim1, 1
    tsa(ji,jj,mbkt(ji,jj),jp_tem) = tsa(ji,jj,mbkt(ji,jj),jp_tem) + qgh_trd0(ji,jj) / e3t_n(ji,jj,mbkt(ji,jj))
  enddo
enddo
```

The OMPLoop transformation correctly refuses to add the parallelisation pragma on it because the dependency analysis returns a possible data dependency. But we know that they are safe (domain knowledge?) because the tweaked OpenACC parallelises them manually with " !$ACC loop independent".

We need to somehow tell the dependency analysis that this indirect access is safe, or alternatively make the return of the dependency analysis more explicit (now is just a string that we need to parse) in order for a version of the domain-specific transformation allow allow this as safe dependencies.

**Comment by arporter** [comment]
Isn't the first one guaranteed to be safe because each loop iteration writes to a different `i,j` location? i.e. we're not parallelising over `k`.

**Comment by sergisiso** [comment]
Aha you are right, the TransformationError in this loops is:
```
Transformation Error: Dependency analysis failed with the following messages:
Error: Variable 'zgru' is written to and the loop variable 'jj' is used in different index locations: zgru(ji,jj,mbku(ji,jj)) and zgru(ji,jj,mbku(ji,jj))
```

**Comment by sergisiso** [comment]
It fails because during the dependency analysis it does the `array_accesses_consistent()` check and in it:
```
 elif first_index != indx:
     # If a previously identified index location does not match
     # the current index location (e.g. a(i,j), and a(j,i) ),
     # then add an error message:
     consistent = False
     self._add_error(
         "Variable '{0}' is written to and the loop variable "
         "'{1}' is used in different index locations: "
         "{2} and {3}."
         .format(signature.var_name,
                 loop_variable.name,
                 signature.to_language(first_component_indices),
                 signature.to_language(component_indices)))
```

@hiker Any ideas how to fix this for `zgru(ji,jj,mbku(ji,jj))`? It seems that if the indices that we aim to parallelize have already been found consistent, we could ignore the additional accesses?

**Comment by nmnobre** [comment]
After some investigation, I found that:

```
DO jj = 1, jpjm1
  DO ji = 1, jpim1
    gru(ji, ji) = gru(ji, jj)
  END DO
END DO
```

Is currently parallelised, when it shouldn't. I must admit I don't know if the current dependency analysis assumes domain knowledge which rules out such cases. For the case you mention, the indirection must be treated as a read of a different variable, which it currently isn't I'm guessing?

**Comment by hiker** [comment]
> @hiker Any ideas how to fix this for `zgru(ji,jj,mbku(ji,jj))`? It seems that if the indices that we aim to parallelize have already been found consistent, we could ignore the additional accesses?

Yes, but I don't think there's a simple fix. I intend to do it properly (which should handle this case), but just don't have time atm. 
Yes, this case might work if we 'remove' identical indices (`ji` in position 1 is the same, so ignore it). But if you consider:
```
do k
   do i
    a(i,k,i,k) = a(i,k,k,i) + 1
```
As far as I can see this is still parallelisable (each `a(i,k,:,:`) is a totally different 2d array, so it doesn't matter what one thread does in that area). And if you remove the first two indices `i` and `k` from the test (because they are the same), you then have the inconsistencies with the next `i` in dimension 3 and 4 :( 

Maybe we could just add a first test: if there exist one dimension that has the same value in all read and write accesses to a variable, and this value is guaranteed to be different for each parallel loop iteration, the loop can be parallelised? Something along the line:

> If there exist loop iterations `i1` and `i2` so that for `a(..., f(i1), ...) = a(..., g(i2), ...) + ... ` (f and g at same dimension) we have:
> `f(i1) = g(i2)  -->  i1=i2` ?
(i.e.: if the same index is used in loop iteration `i1` and `i2`, then `i1` must be `i2`).

Maybe this is actually what you meant above when you wrote 'when the index we parallelise is consistent'? Note it's not sufficient to just compare if the index expressions are the same, e.g.: `a( (i-2)^2 ) = a( (i-2)^2 ) + 1`: the index expressions are the same, but we would still access the same indices for `i=1` and `i=3`.

In this example:
```
    zgru(ji, jj, mbku(ji, jj)) = gru(ji, jj)
```
we have `f(i) = g(i) = i` for the first dimension. So for two loop iterations `ji1` and `ji2` we get:  `f(ji1) = ji1 = g(ji2) = ji2` --> `ji1=ji2`, which is true, so the loop can be parallelised over `ji`.
```
a(i*i+i) = a(i) + 1
```
cannot be parallelised: `f(i)=i*i+i`, and `g(i)=i`, so we compare: `i1*i1+i1 = i2` from which does not follow `i1=i2` (e.g. i1=1, i2=2).
```
gru(ji, ji) = gru(ji, jj)
```
cannot be parallelised over the `jj` loop:

1. First index: for loop iteration `jj1 ` and `jj2`, if `f(jj1) = ji = g(j2) = ji`, then it does **not** follow that `jj1=jj2` 
2. Second index: for loop iterations `jj1` and `jj2`, if `f(jj1) = ji = g(jj2) = jj2`, then it does **not** follow that `jj1=jj2`.

So the loop cannot be parallelised over `jj`. It can be parallelised over `ji`:
1. First index: for loop iteration `ji1` and `ji2`, if `f(jj1) = ji1 = g(ji2) = ji2` (LHS and RHS above), then `ji1=ji2`.

I am not sure if this is a band-aid or a proper solution - e.g. is this sufficient, or necessary, or both?? Don't have my compiler book at hand. I'm happy to get back into this, skip the loop fusion dependency analysis, and try fixing parallelization first? 

Sympy seems to be able to do the right maths. For loop iterations `x1` and `x2`:
```
>>> sp.nonlinsolve([x1 - x2], x1)
{(x2,)}
```
So `x1-x2 == 0` requires `x1=x2` --> can be parallelised
And:
```
>>> sp.nonlinsolve([(x1-2)**2 - (x2-2)**2], x1)
{(x2,), (4 - x2,)}
```
Showing that if the indices `(x-2)^2` are the same, the loop iterations can be the same (`x1=x2`), but there is a second solution (`x1 = 4-x2`) --> cannot be parallelised  (technically we could also check if the second solution is part of the iteration space - if the loop is from 0 to 1, then the second solutions (4 and 3) are not possible, so the loop could still be parallelised).

Easy and quick solution: add an option to disable this test? How urgent is this?

**Comment by hiker** [comment]
> After some investigation, I found that:
> 
> ```
> DO jj = 1, jpjm1
>   DO ji = 1, jpim1
>     gru(ji, ji) = gru(ji, jj)
>   END DO
> END DO
> ```
> 
> Is currently parallelised, when it shouldn't. I must admit I don't know if the current dependency analysis assumes domain knowledge which rules out such cases. For the case you mention, the indirection must be treated as a read of a different variable, which it currently isn't I'm guessing?

Hmm - I would have thought that this prints a warning? I considered this case in the dependency tools, but not the fact that LHS and RHS use the same variable :( My example in the comments is:
```
            # do j=1, n
            #    a(1) = b(j)+1
            #    c(j) = a(1) * 2
            # enddo
```
and in this case `a(1)` should be a thread private variable, then it can be parallelised.

Ah, I see it now - because it's the same variable, it doesn't detect that the access to this is loop independent, it mixes all accesses together :(  Thanks, good test case.

But I think the above test should be ... at least more correct (that's all I am willing to say without consulting a book :)  )

**Comment by sergisiso** [comment]
> Easy and quick solution: add an option to disable this test? How urgent is this?

Not urgent. We have just finish reporting the Nemo OpenMP performance and I was listing the things that I noticed that were still not handled properly and could be targeted during the next phase of the project. I rather take the time to get the proper solution that fits with the dependency analysis instead of making specific exceptions.

**Comment by nmnobre** [comment]
> > @hiker Any ideas how to fix this for `zgru(ji,jj,mbku(ji,jj))`? It seems that if the indices that we aim to parallelize have already been found consistent, we could ignore the additional accesses?
> 
> Yes, but I don't think there's a simple fix. I intend to do it properly (which should handle this case), but just don't have time atm. Yes, this case might work if we 'remove' identical indices (`ji` in position 1 is the same, so ignore it). But if you consider:
> 
> ```
> do k
>    do i
>     a(i,k,i,k) = a(i,k,k,i) + 1
> ```
> 
> As far as I can see this is still parallelisable (each `a(i,k,:,:`) is a totally different 2d array, so it doesn't matter what one thread does in that area). And if you remove the first two indices `i` and `k` from the test (because they are the same), you then have the inconsistencies with the next `i` in dimension 3 and 4 :(
> 
> Maybe we could just add a first test: if there exist one dimension that has the same value in all read and write accesses to a variable, and this value is guaranteed to be different for each parallel loop iteration, the loop can be parallelised? Something along the line:
> 
> > If there exist loop iterations `i1` and `i2` so that for `a(..., f(i1), ...) = a(..., g(i2), ...) + ... ` (f and g at same dimension) we have:
> > `f(i1) = g(i2)  -->  i1=i2` ?
> > (i.e.: if the same index is used in loop iteration `i1` and `i2`, then `i1` must be `i2`).
> 
> Maybe this is actually what you meant above when you wrote 'when the index we parallelise is consistent'? Note it's not sufficient to just compare if the index expressions are the same, e.g.: `a( (i-2)^2 ) = a( (i-2)^2 ) + 1`: the index expressions are the same, but we would still access the same indices for `i=1` and `i=3`.
> 
> In this example:
> 
> ```
>     zgru(ji, jj, mbku(ji, jj)) = gru(ji, jj)
> ```
> 
> we have `f(i) = g(i) = i` for the first dimension. So for two loop iterations `ji1` and `ji2` we get: `f(ji1) = ji1 = g(ji2) = ji2` --> `ji1=ji2`, which is true, so the loop can be parallelised over `ji`.
> 
> ```
> a(i*i+i) = a(i) + 1
> ```
> 
> cannot be parallelised: `f(i)=i*i+i`, and `g(i)=i`, so we compare: `i1*i1+i1 = i2` from which does not follow `i1=i2` (e.g. i1=1, i2=2).
> 
> ```
> gru(ji, ji) = gru(ji, jj)
> ```
> 
> cannot be parallelised over the `jj` loop:
> 
> 1. First index: for loop iteration `jj1 ` and `jj2`, if `f(jj1) = ji = g(j2) = ji`, then it does **not** follow that `jj1=jj2`
> 2. Second index: for loop iterations `jj1` and `jj2`, if `f(jj1) = ji = g(jj2) = jj2`, then it does **not** follow that `jj1=jj2`.
> 
> So the loop cannot be parallelised over `jj`. It can be parallelised over `ji`:
> 
> 1. First index: for loop iteration `ji1` and `ji2`, if `f(jj1) = ji1 = g(ji2) = ji2` (LHS and RHS above), then `ji1=ji2`.
> 
> I am not sure if this is a band-aid or a proper solution - e.g. is this sufficient, or necessary, or both?? Don't have my compiler book at hand. I'm happy to get back into this, skip the loop fusion dependency analysis, and try fixing parallelization first?
It's sufficient, in the sense you'll never parallelise code you shouldn't, but not necessary, in the sense you'll not parallelise code you could. Take, e.g.:
```
DO jj = 2, jpj
  DO ji = 2, jpi
    gru(ji, jj) = gru(ji-1, jj-1)
  END DO
END DO
```
where the inner loop can be parallelised. I think I can help with this if the team agrees 🙂
> 
> Sympy seems to be able to do the right maths. For loop iterations `x1` and `x2`:
> 
> ```
> >>> sp.nonlinsolve([x1 - x2], x1)
> {(x2,)}
> ```
> 
> So `x1-x2 == 0` requires `x1=x2` --> can be parallelised And:
> 
> ```
> >>> sp.nonlinsolve([(x1-2)**2 - (x2-2)**2], x1)
> {(x2,), (4 - x2,)}
> ```
> 
> Showing that if the indices `(x-2)^2` are the same, the loop iterations can be the same (`x1=x2`), but there is a second solution (`x1 = 4-x2`) --> cannot be parallelised (technically we could also check if the second solution is part of the iteration space - if the loop is from 0 to 1, then the second solutions (4 and 3) are not possible, so the loop could still be parallelised).
> 
> Easy and quick solution: add an option to disable this test? How urgent is this?

**Comment by hiker** [comment]
I had already started to work on the proper solution, but put it aside to focus on training ... from which I now need a break :) I'll dig out my notes, and revive my branch. FWIW, I am following https://www.amazon.com/Optimizing-Compilers-Modern-Architectures-Dependence-based/dp/1558602860 (and didn't remember the details when I wrote the above statement yesterday night :) )

**Comment by nmnobre** [comment]
Ah! I think it's the first time I've come across that one. I still use [this gem](https://dl.acm.org/doi/10.5555/572937) that my supervisor was kind enough to leave me when he retired. Probably slightly outdated nowadays. We could look into using algebraic methods for dependence resolution as well if we think they're worth our efforts. 😊

**Comment by sergisiso** [comment]
With PR #1693 the loops that this issue referred to are now parallelised with OpenMP
