### ISSUE TITLE
invalid adjoint kernel module names

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1717]
adjoint kernel module names are currently the tangent linear name with `_adj` appended. This does not conform to the `_mod _code _type` LFRic convention. The type and code names are also not updated. `psyclone-kern -gen stub xxx.F90` complains about this.

**Comment by arporter** [comment]
I discussed this with Ian and Christine. Ian suggested it would be good to replace `tl_` with `adj_` if the existing kernel/module name has that as a prefix. Otherwise, we could just add `adj_` as a prefix.
Note that PSyclone itself doesn't complain about our abuse of the naming convention (but that doesn't make it right!).

**Comment by rupertford** [comment]
Created branch [1717_invalid_adjoint_names](https://github.com/stfc/PSyclone/tree/1717_invalid_adjoint_names)

**Comment by rupertford** [comment]
The type and code metadata values will not be updated in this PR as we are waiting for the proper parsing of LFRic metadata. At the moment we are working on gocean metadata, see #1633. After that we will move to LFRic metadata.
