### ISSUE TITLE
Handle Induction Variables for dependency analysis

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1751]
We should support at least two typical use cases:

1. `im = i - 1`  (or in general: `var = f(i)` ):
    This would require replacing all access to `im` with `(i-1)` (in the copy of the psyir tree that the dependency analysis is working on).
2. `k = k + n` (or in general: `var = f(var)`
    In simple linear cases we can compute `k` depending on the initial value: `k = k_0 + (i-1)*n` or `k = k_0 + i*n` (depending on where k is modified - at the beginning or the end of the loop). This is more complicated (e.g. what if k should be set 'in the middle of a block - in the section before we need to have the 'previous' k value based on `(i-1)`, while in later code we need to use `i`).

Both cases would require the functionality to replace a reference with (a copy I assume) of an expression.

**Comment by sergisiso** [comment]
I see some alternatives:
- provide the sympy solveset with a system of equations with the equality we are checking + all the induction variables that appear before it in the loop. This seems the best solution to me since it will support anything we add in out sympywriter in the future without worrying about properly transforming the tree. But I don't know if it becomes too costly to solve system of equations for each check?
- do the modifications in a copy of the tree and then do the array indexes distance check.
- return an error code and be the responsibility of the user to apply the necessary transformations (my least preferred) since it will provide outputs a bit more different from the original code.

**Comment by hiker** [comment]
@sergisiso , I have the following functionality implement, which has some restrictions, but would handle your case already:
```
do ji = 1, jpi
   jj = ji + 1
   mask(jj, 1) = umask(jj, 1)
  end do
```
-->
```
do ji = 1, jpi, 1
  mask(ji + 1,1) = umask(ji + 1,1)
enddo
jj = jpi + 1
```

Restrictions:
- No 'recursive' variables, i.e. variable on lhs also used in rhs  (k=k+3)
- Only simple scalar (no StructureReferences, e.g. `a%b = i + 3`

These cases are detected (as in: the transformation won't do anything wrong, it will just not replace them).

If this by itself is useful enough, I could submit a PR soonish, which would introduce this as a transformation, which at this stage you would have to apply before calling the dependency analysis. Integrating this could be done as a separate PR later - just to keep PR size small.

**Comment by hiker** [comment]
I just realised that the 'end' value is computed incorrectly - using the `stop` value of the loop can be incorrect if the step size is not 1, e.g.:
```
do i=1, 4, 2
    im = i-1
enddo
```
At the end of the loop `im` will have the value `3-1` (since `i` is 1, 3, then 5 but will not execute the loop body for `i=5`), so the statement to add at the end of the loop is:
```
im = i - 2 - 1
```

**Comment by hiker** [comment]
The transformation surprisingly works with structures, e.g.:
```
type(my_type) :: b
do i = 1, 10, 5
   b%a = i+1
   a(b%a) = 1+(b%a+1)*b%a
end do

do i = 1, 10, 5
   a(i + 1) = 1 + (i + 1 + 1) * (i + 1)
enddo
b%a = i - 5 + 1
```
It just means we need to add more tests (e.g. while I exclude array expressions, there could still be array expressions somewhere in one of the structures)

**Comment by sergisiso** [comment]
Closing this issue since we now have the ReplaceInductionVariableTrans. For now it still needs to be applied manually.
