### ISSUE TITLE
Re-write unit-tests for builtins

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1796]
Currently the majority of the builtin tests are in `domain/lfric/lfric_builtins_test.py` and `domain/lfric/lfric_integer_builtins_test.py` but they are huge. Therefore a new `domain/lfric/builtins` directory has been created and tests for each builtin should be moved to a separate file in that directory. In common with our usual working practices, this should be done *without* any other modifications to simplify the review process.

EDIT: as discussed below, the bulk of the test code that we currently have for Builtins is unnecessary. This issue should therefore solve the problem by simplifying the existing tests.

**Comment by sergisiso** [comment]
I disagree, it is true that the file is huge (it has been a pain to change the syntax to update to the backend - and I just done a small part of it), but the problem is that it says: "Also test with and without annexed DoFs being computed as this affects the generated code" and also each test is parametrised with and without distributed_memory.

Then it generates the full 4 expected invokes (including declarations, initialisations, distributed_memory) and compares them all.

However, I haven't found any test where the builtins are affected by these, and searching the lfric_builtins.py these keywords do not appear anywhere. E.g. for "aX_plus_Y", the generated code is always:
```
DO df = loop0_start, loop0_stop, 1
     ! Built-in: aX_plus_Y (real-valued fields)
     f3_data(df) = 0.5_r_def * f1_data(df) + f2_data(df)
enddo
```
(is this not the case for any other builtin?)

What happens is that the distributed_memory and annex_dof are affected by the metadata of the built-in object. But it is up to these classes/code_generation to test that they do the right thing given some field metadata values (which they already do). And of course it also not this file responsibility to check the invoke declarations and initialisations.

**Comment by arporter** [comment]
OK, so the crux of it is that we need to re-write the tests to purely cover the corresponding classes. As Sergi points out, the implementation of these is short so our tests can be too :-)
