### ISSUE TITLE
Replace Operation nodes that represent intrinsics with IntrinsicCall.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1987]
In #1366 we introduced the new `IntrinsicCall` node to represent calls to intrinsic functions/routines. This was primarily driven by the need to support optional arguments but now that we have it it makes sense to treat all intrinsics in the same way and therefore this issue will change those currently represented as Operations to be `IntrinsicCall` s instead.

@sergisiso has pointed out that this has implications for optimisations/parallelisation - currently operations are permitted when parallelising code but calls are not. We will therefore need some way of distinguishing those that are safe (perhaps the fact that they are an `IntrinsicCall` as opposed to a `Call` will be sufficient?).

**Comment by sergisiso** [comment]
I agree with this. At least for the intrinsics with:
- optional parameters (currently can be Unary/Binary/Nary - which make it tricky to search them in the tree),
- named args (currently  append_named_arg, insert_name_arg, _reconcile implementation is duplicated in Operation and Call)
- that are Narys (look a bit strange)

We can get rid of all this forced functionality if they are IntrinsicCalls 

> We will therefore need some way of distinguishing those that are safe (perhaps the fact that they are an IntrinsicCall as opposed to a Call will be sufficient?).

I won't be sufficient because there are IntrinsicCalls that are not thread_safe (e.g. the allocate intrinsic being added). By contrast there are normal calls that are safe and would be good to not break the parallelisation for them (e.g. CodedKern calls or calls to regular subroutines annotated with pure - given no data dependencies).
I think we need to implement some concept of pure/thread_safe and elemental (Operations already has this last one).

**Comment by sergisiso** [comment]
I am going to address this next, with Fortran Intrinsics being IntrinsicCalls we can:
- remove the named arguments infrastructure from operators
- remove the Nary Operation
- use is_pure in the dependency_analysis/transformations/scripts to decide if it is allowed in a parallel body
- use is_inquiry in the dependency_analysis, reference_accesses to prevent the data dependency
- use is_elemental in the range2loop to decide how they are converted to a loop
- use a new is_avalilable_on_gpus to decide if it is allowed in a GPU region
(and implement each of this in just one place - one thing to check instead of duplicating it for Calls and Operators)

Then all remaining operators are guaranteed to be pure/touch_the_data/elemental/available_on_gpu so no special case or checks are needed in the transformations for them.

It also has the advantage that for user defined functions, if we can properly get or deduce the attributes above, we can also parallelise and bring the to GPUs using the same checks on the transformations.
