### ISSUE TITLE
Wrong hoisting of assignment out of a loop

### ISSUE THREAD

**Issue by nmnobre** [stfc/PSyclone#2082]
Most likely reason being failing dependency analysis because of `CodeBlock`.
Happens with `omp_gpu_trans.py` on `icerst.f90`.

**Comment by arporter** [comment]
Could you give more details @mnobre, i.e. some code fragments that demonstrate the problem?

**Comment by sergisiso** [comment]
It was in cases like:
```
do i=1,10
   write(zchar1, '(I2.2)') i
   zanm = 'e_s' // '_l' // scahr1
enddo
```
where zanm was being hoisted by HoistTrans even if it is rewritten every loop. We don't know if it is because the read is in a CodeBlock, the write is in a CodeBlock, one of the CodeBlocks does not return the zchar1 symbol as used or a combination of those. Probably all these cases need to be tested.

**Comment by sergisiso** [comment]
Just to confirm that there are 2 issues here:
- Codeblock does not have reference_access, and therefore it misses its dependencies.
- HoistTrans does not check for side effects (it should not validate CodeBlocks and Calls not guaranteed to be pure)
Both need to be fixed.
