### ISSUE TITLE
[LFRic] Renaming and moving DynInvoke and DynKern 

### ISSUE THREAD

**Issue by mo-lottieturner** [stfc/PSyclone#2091]
in attempting to tackle #1545 the same circular dependency has cropped up, this time with DynInvoke and DynKern. Thus, splitting these out (and renaming while I'm at it)

**Comment by hiker** [comment]
@mo-lottieturner, just a quick comment: sometimes you can replace an import at the top of a file with an import where it is actually needed. This needs a pylint directive to avoid a warning, e.g.:
```
        # Avoid circular import
        # pylint: disable=import-outside-toplevel
```

And sometimes it helps to not import a module from its directory, but from its source file. Gee, that sounds incomprehensible, so as example:
```
from psyclone.parse import RoutineInfo
from psyclone.parse.routine_info import RoutineInfo
```
(You won't see these files in master, it's from a branch I am currently working on).

The second kind of import avoids the need that `__init__` is loaded, which can sometimes break a circular dependency.

The first one requires that `RoutineInfo` is defined in `psyclone/parse/__init__.py`. This can trigger circular dependencies. (when while importing `__init__`  something else needs the same `__init__` because it is importing from the directory, in the example above `parse`, instead of the source file `parse/routine_info`. This can sometimes be avoided by changing the order in which files are imported in __init_ as well - though this then again clashes with our coding style of sorting them alphabetically).


And if you knew all of that, my apologies ;)

**Comment by arporter** [comment]
Just to echo what @hiker has said, although I agree that we want to restructure and thus minimise the number of potential circular dependencies it is important to try to keep changes as self-contained as possible otherwise getting them onto master becomes very difficult! What I'm saying if that a change starts to spiral and touch a lot of source files then it's sometimes best to step back and break it into a few, smaller pull requests.

**Comment by mo-lottieturner** [comment]
@arporter @hiker Thank you both for the tips! We discussed trying to import the dependencies differently when we first discovered the bug, but as the end goal is to separate them out anyway, we decided to go that route - especially as Iva is on leave this week, and it's not something I've done before so I'm more likely to hit unexpected problems that I can't untangle

**Comment by mo-lottieturner** [comment]
Dependencies found so far:
DynInvoke needs DynInvokeSchedule
DynInvokeSchedule needs DynKernCallFactory
