### ISSUE TITLE
[nemo] PSyclone loses ‘ELEMENTAL’ and ‘IMPURE ELEMENTAL’ subroutine prefixes

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2119]
Simon has reported that:

PSyclone appears to falsely drop ‘ELEMENTAL’ and ‘IMPURE ELEMENTAL’ subroutine prefixes. ‘ELEMENTAL’ and ‘IMPURE ELEMENTAL’ prefixes have recently been added to some functions in NEMO ‘main’. In builds without AGRIF processing these functions appear to be reproduced correctly by PSyclone, but after AGRIF processing the prefixes additionally apply to subroutines and seem to disappear during PSyclone processing.

We've discussed having the `ELEMENTAL` property previously. I guess this would need an extension to `RoutineSymbol`.

![image](https://user-images.githubusercontent.com/17409212/234906574-63149d4f-ef4f-4846-a19d-eb5354fc9a2e.png)

**Comment by arporter** [comment]
@sergisiso touched on this for IntrinsicCall in https://github.com/stfc/PSyclone/issues/1987#issuecomment-1359024597.

**Comment by arporter** [comment]
(Running fparser2 on `elemental.f90` *does* correctly reproduce the 'elemental' prefix on the subroutine so this is a problem with the PSyIR frontend.)

**Comment by sergisiso** [comment]
Ah, I misunderstood what the agrif comment meant. So we drop them no matter what (for subroutines). We need to fix this.

**Comment by arporter** [comment]
I'm beginning to implement support for these features but am unsure how to design it. I was going to add `is_elemental` and `is_pure` to the `RoutineSymbol` class but then I looked at `Routine` and it already has `is_program`. Also, it is the `Operation` node that already has `is_elemental` so maybe these new properties should go in the `Routine` node rather than `RoutineSymbol`. What do you think @sergisiso?

**Comment by arporter** [comment]
Should have asked @rupertford too really :-)

**Comment by arporter** [comment]
In fact, if I look at the Fortran backend then it currently works by querying the properties of the nodes it encounters. Whether a routine is PURE or ELEMENTAL or whatever has no effect on the Symbol representing it. I shall therefore implement the new support in the Routine node. (Unless anyone comes up with a good argument against it.)

**Comment by sergisiso** [comment]
Operation has `is_elemental` but really we are moving intrinsic operations to `IntrinsicCalls`, which are represented by a `IntrinsicSymbol` that inherits from `RoutineSymbol`. So I sypport  fully moving the attribute to RoutineSymbol. (since the remaining operations +,-,*,/, ... are always elemental and don't need the distinction)

Also it is information that both the Caller and Callee need to be aware of, so it make sense to be in the RoutineSymbol (or routine datatype but we don't have this yet). And maybe Call and Routine can have helper functions that check the symbols but don't store the info themself.

Also be aware that imported symbols that we don't know if they are elemental shouldn't be true nor false (maybe None?). As there are situations (e.g. range2loop) that we can not resolve until knowing the full symbol information.

**Comment by arporter** [comment]
Ah! Those are good points. I'll change my implementation :-) I think we'll need some sort of 'unknown' value as I get uneasy relying on distinguishing the difference between `None` and `False`.
