### ISSUE TITLE
Dev Guide and PSyAD UG builds failing on RTD

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2126]
The Sphinx builds are failing with, e.g.:

    Extension error:
    Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)

**Comment by amotl** [comment]
Dear Andy,

when you are using RTD, you can mitigate the problem by using a more recent build environment with a newer OpenSSL version. Otherwise, you will probably need to nail the dependency to `urllib3<2`.

With kind regards,
Andreas.

#### References
- https://github.com/crate/crate/pull/14052
- https://github.com/crate/crate-operator/pull/511

**Comment by arporter** [comment]
It looks like we have to use a RTD config file to control the OS version of the Docker container used by RTD. We can't use a config file because we build four different documents from a single Project repo. Therefore, until such times as the default OS used by RTD is upgraded, we have to pin urllib3 (thanks @amotl).
