### ISSUE TITLE
Add "write(*,*)" 'profiling' PSyData library

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2186]
It would be really useful if there was a PSyData wrapper that just printed out "I'm entering this region..." and "I'm leaving this region...". It might be messy when running MPI-parallel but it would help a lot with GPU debugging.

**Comment by hiker** [comment]
Use the template library, it does exactly that:
```
$ cd .../examples/gocean/eg5/profile
$ make template
...
./profile_test.template
...
Allocating C-T field with bounds: (1:   6,1:   6), internal region is (2:   4,2:   4)
 PreStart called for module 'invoke_0' region 'r0'
 PostEnd called for module 'invoke_0' region 'r0'
 PreStart called for module 'invoke_1_update_field' region 'r0'
 PostEnd called for module 'invoke_1_update_field' region 'r0'
```
Some(!) of the profiling libraries can print this information in addition to their normal behaviour by setting the environment variable PSYDATA_VERBOSE to 1 or 2 (2 is more verbose, but doesn't make a difference for profiling libs). I think it does not work for nvidia (since the nvidia wrapper does not call the psydata base class).
