### ISSUE TITLE
PSyclone fails to interpret a variable declaration featuring the same variable name in the assignment

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#2247]
I can't explain this very well, but I have a very small test showing the failure:
```
def test_type_case(fortran_reader):
    code = '''module test
    Real :: temp_max_sph = LOG(HUGE(temp_max_sph))/2.0
    end module test
    '''

    psyir = fortran_reader.psyir_from_source(code)
```
Error is:
```
>       raise SymbolError(f"No Symbol found for name '{name}'.")
E       psyclone.psyir.symbols.symbol.SymbolError: PSyclone SymbolTable error: No Symbol found for name 'temp_max_sph'.
```
at `../../../psyir/frontend/fparser2.py:361`

**Comment by LonelyCat124** [comment]
@sergisiso I guess this is related to the change you made for #1419 not supporting this behaviour/PSyclone not understanding it?

**Comment by sergisiso** [comment]
The problem is that HUGE is an "Inquiry Intrinsic Function" which is the class of intrinsic that do not touch the data itself but just look at the type. Similar to SIZE, LBOUND, ...

For this reason there is no data dependency and no recursive declaration with the LHS.

I am introducing the knowledge that this intrinsics are "inquiry" class in a branch and then we can maybe do somthing about it but for a quick solution you could just replace the original line with:
`  Real :: temp_max_sph = LOG(HUGE(0.0))/2.0`

**Comment by sergisiso** [comment]
Another more generic solution is assume the original is right and move the initialization block fparser2.py:1931 after the symbol has already been introduced to the symbol table ~ fparser2.py:2000

**Comment by LonelyCat124** [comment]
Did someone fix this somewhere? I'm not seeing the test at the top of this issue fail on current master.
@arporter @sergisiso

**Comment by sergisiso** [comment]
This has been fixed, the intrinsic_call reference_access does not include the data dependencies for the inquiry functions. (There is a static dependency that we don't capture now, but this is a separate issue)
