### ISSUE TITLE
Dependence analysis bug?

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2303]
In #2301 I've been having trouble getting one of the doctests to work. I've found that adding:

                do ji=2, 10
                   mask(ji,ji) = mask(ji,ji) + mask(ji-1,ji)
                end do

to `tests/psyir/tools/dependency_tools_test.py::test_arrays_parallelise` demonstrates the problem. This loop cannot be parallelised but `can_loop_be_parallelised` returns True.

Would you mind taking a look @hiker?

**Comment by arporter** [comment]
If I do `mask(ji, ji-1)` then the dependence analysis does spot that the loop cannot be parallelised.

**Comment by hiker** [comment]
> If I do `mask(ji, ji-1)` then the dependence analysis does spot that the loop cannot be parallelised.

Not entirely sure what you mean with this. Do you just change the last term (`mask(ji-1,ji)`->`mask(ji, ji-1)`)? Or do you write to these indices?

**Comment by hiker** [comment]
I admit I got tricked at first, too. It was only when I single-stepped and noticed why it is flagging it as ok that I realised that it is indeed correct (thanks to your code review there were nice comments 😃  ).  And yes, the DA system is pretty good (with the caveat that some of the more advanced algorithms are not yet implemented in PSyclone, since I doubt we encounter them in a real application, but if we do, we can expand it). And that hopefully also explains my reluctance to introduce a 'safe-write' access, since then all these algorithm need to be re-evaluated (if not re-written :)  ). 
But I have to admit, I am proud that the DA proved better than the two of us together :P
