### ISSUE TITLE
[LFRic] bug when profiling applied within a Loop

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2796]
Jaffery has found that applying ProfileTrans to nodes within a loop generates incorrect code. The `profile_psydatatype` is imported correctly but no variable with that type is ever declared. If I alter the script to make sure the profiling is put *outside* the loop then the associated variable is declared correctly. I suspect this is because we currently handle everything within a loop with PSyIR and everything outside with the old `gen_code` method.

If it isn't too hard to fix then it would be good to get this done before 3.0 is released.

**Comment by hiker** [comment]
Reproduced, and confirmed: if the psydata code is created using PSyIR, the declaration is missing, if gen_code is called, it worked. I'll try to fix it for 3.0

**Comment by arporter** [comment]
Actually Joerg, this will probably be fixed by @sergisiso in his work to move LFRic over to PSyIR completely. Since putting profiling inside a loop is probably not the best thing to do, I think this could wait rather than us rushing to get it done.

**Comment by hiker** [comment]
I do have solution, see https://github.com/stfc/PSyclone/commit/eb7e22ca1fd5a9fb9f3dbb470b1eadf1799b5f71 or branch   2796_fix_profile_nodes_inside_of_lfric_loops
It needs to be cleaned up (or refactored, move the code from loop into psydata node), and needs test. @arporter, let me know if you want me to finish it.
The (to me) strange thing: why on earth is the import statement added, since it's in the same symbol table as the missing variable. That would need some additional debugging ;)
