### ISSUE TITLE
Add child index of node in Schedule view() method output

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#303]
As noted in @arporter's [comment](https://github.com/stfc/PSyclone/pull/218#pullrequestreview-205641006), including the child index of each node in the Schedule in the `view()` method output would help identifying nodes for transformations. E.g.:

    Schedule[invoke='invoke_0']
        [0] Loop[type='',field_space='v3',it_space='None']
            [0] KernCall rhs_v3_code(rhs) [module_inline=False]
            [1] KernCall solver_v3_code(pressure_density,rhs) [module_inline=False]

**Comment by sergisiso** [comment]
I agree this could be useful. But I think the indexing only makes semantic sense for the Schedule as it is a ordered sequence of statements (as in your example). With the IfBlocks and upcoming Loop structure it won't be future-proof to reference children by index. Maybe we can add an optional flag into view: `view(self, indent=0, semantics=False`) and when set to `True` print something like this : 
```
Schedule[invoke='invoke_0']
    0 : Loop[type='',field_space='v3',it_space='None']
        start_expr : Literal [value='1']
        end_expr : Reference [name='N']
        step_expr : Literal [value='1']
        loop_body : Schedule[]
            0 : KernCall rhs_v3_code(rhs) [module_inline=False]
            1 : KernCall solver_v3_code(pressure_density,rhs) [module_inline=False]
```
I changed `[ ]` to `:` because we already have squared brackets in the attributes, but I am happy to try different notations to see what looks best.

**Comment by sergisiso** [comment]
After a chat here, we proposed to implement it the other way around. By default print the detailed tree with semantic/index information for all nodes and include all children.
Then add a `compact` flag into the `view()` methods to print a tree with less information to provide a 'nice' conceptual representation of the tree.

**Comment by sergisiso** [comment]
I will implement this issue together with #385 (PSyIR Loops), they are not completely related and the PR is already growing more than I wanted but both will change most of the strings that `view()` provides in the tests and documentation. So it makes sense to update all of them just in one go.

**Comment by arporter** [comment]
Sam Cusworth (MetOffice) and Joerg have independently brought up the problem of working out which nodes in a Schedule are to be targeted with a transformation so I have agreed to take this one on.

**Comment by arporter** [comment]
In working on this Issue I've been trying to improve the implementation of `view()` and have currently arrived at a solution where `view()` just creates a colour-coded string that is passed to a `base_view()` method which prints it (inserting indent and index if required) before calling `view()` on all children.
However, this then raises the question of why we don't just have the `__str__` method create the class-specific description with the tree traversal itself done using the visitor pattern? We could overload the `__str__` method so that it takes an optional parameter controlling whether or not to add colour codes. What do @hiker, @TeranIvy, @rupertford and @sergisiso think?

**Comment by sergisiso** [comment]
I am not sure the `str()` function accepts optional arguments even if `__str__()` accepts them. You should check it before doing your proposed implementation.


Also, also another idea is that there seems to be a lot of replicated code in all the view methods, you could rename your `view_base()` to just `view()`  in the Node class and delete all the other `view()`s. This common `view()` would print the pattern `(indent)(index)<colored_name()>[<porperties_string()>]\n` and call the children with appropriate indent and index. Then just have a colored_text() in all Nodes (we already have) and a new properties_string() method (which we can reuse for the `__str__`). It is possible that then we can just write a common `__str__` method. Would that simplify things?

**Comment by arporter** [comment]
Possibly although I don't think there's a one-size-fits-all way of constructing the string - sometimes we have '()' and sometimes we don't. However, maybe that's something else we should tidy up.
You're right about `str()` - I tried it and I asked google: https://stackoverflow.com/questions/7353486/why-str-cant-get-a-second-parameter-when-str-can
