### ISSUE TITLE
Fix pytest deprecated warnings.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#326]
Running the test suite with more recent versions of pytest gives (many) deprecation warnings, e.g.:

    psyclone_test_utils.py:115
      /home/me/Projects/GungHo/PSyclone/src/psyclone/tests/psyclone_test_utils.py:115:   PytestDeprecationWarning: the `pytest.config` global is deprecated.  Please use `request.config` or `pytest_configure` (if you're a pytest plugin) instead.
    TEST_COMPILE = pytest.config.getoption("--compile")

**Comment by arporter** [comment]
This looks like it may be tricky to solve. The recommended way to get at pytest configuration settings is now via the `request` object. AFAICS, only fixture functions can be provided with this `request` object (https://docs.pytest.org/en/latest/fixture.html#request-context). Therefore, we would need a new test fixture that maybe provides the `Compile` object to a test.

**Comment by arporter** [comment]
e.g. a test would now look like:

    def test_field(GOcean1p0Builder):
        ...
        psy = PSyFactory(...)
        assert GOcean1p0Builder.code_compiles(psy)

where:

    @pytest.fixture
    def GOcean1p0Builder(tmpdir, request):
        test_compile = request.config.getoption("--compile")
        ...
        return GOcean1p0Build(tmpdir)

What do you think @hiker (you know more about fixtures than I do :-) )?

**Comment by hiker** [comment]
I had a look at this, and you are right. This unfortunately means that it is not easy :(

pytest imports the tests before calling a session fixture in conftest. This means that we can't use a command line option to specify the value for COMPILE (since COMPILE will be defined too late). But this is the only supported option to get access to the config option (and therefore to the command line) - so, a bit of a problem :(

ATM it works because when importing a test file, it will import psyclone_test_utilities, which sets @Compile.COMPILE based on pytest.config.

My suggested solution:
we remove the decorator that will cause some test to be skipped, and instead add a test inside the function:
```
@Compile.COMPILE
def test_compiler_works(tmpdir):
```
would become:
```
def test_compiler_works(tmpdir):
   If not Compile.COMPILE:
    pytest.skip("Compilation not enabled")
```
(untested, but it is supposed to work according to the documentation).  Am happy to do this, let me know.

**Comment by hiker** [comment]
I only now fully read your comment. Yes, I think that should work, but it does not solve the problem that you want to mark certain tests as skipped (e.g. then using --compile, then opencl a compile test is skipped). Which then requires a runtime check like above anyway. So tbh, I don't see a good advantage of adding a new fixture - the one auto-use can query the config object to set compiler and compile flags.

And I quickly confirmed that the following code works:
```
    if not Compile.TEST_COMPILE:
        pytest.skip("Compilation disabled")
```
This would still mark a test as 'skipped'.

Let me know if you want me to fix this up.

**Comment by arporter** [comment]
Great - if that's a simpler fix then I'm happy. (I hadn't thought about the issue of having tests skipped when I wrote my original comment.) If you're happy to do it I'm even happier :-)
