### ISSUE TITLE
Test version 0.0.4 of fparser and update documentation

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#33]
The bug in fparser's handling of `class(my_class)` declarations has been fixed in release 0.0.4.
In this issue we will update the documentation to specify this version (and check that PSyclone works OK with it).

**Comment by arporter** [comment]
Working on branch `fparser_0p0p4`. Have updated the documentation and checked that all tests pass or xfail. @rupertford This is such a tiny piece of work that maybe it could be rolled into making the 1.4 release of PSyclone?

**Comment by rupertford** [comment]
Yes, I am happy to add this in before 1.4 if we agree to add it in. However, I would like to moan about this. I don't see why we need to update PSyclone here. As far as I am aware PSyclone will work equally well with fparser 0.0.2 or fparser 0.0.4. There are no tests or examples that rely on 0.0.4 are there?. It is LFRic that need a new version of fparser. So why do we need to update PSyclone?

**Comment by TeranIvy** [comment]
I installed fparser 0.0.2 separately anyway for the current PSyclone 1.3.3 we have and I don't see the problem in replacing it with 0.0.4 and leaving the rest as it is if LFRic needs it soon. This way PSyclone 1.4 needn't be hurried and the new parser can be included as well. Would that work for both of you? BTW, when do you plan to roll out PSyclone 1.4 and is there a chance that the updated (renamed and added) built-ins could be included?

**Comment by rupertford** [comment]
Hi Iva, yes that was my point, you just need to upgrade fparser and can choose separately whether to upgrade PSyclone. If there are dependencies then pip allows you to specify them so installing one package might upgrade another, but there are no dependencies here, psyclone currently does not install via pip and you (the Met Office) don't use pip in any case :-).

We are planning to push out a new release quickly (probably tomorrow) which includes CMA support as Eike and Chris are waiting on this. We thought CMA support warranted a jump from 1.3.* to 1.4.* as it is a significant addition to the API. So no, I don't think the updated builtin's or the dependence analysis will be included. However, don't worry, making new releases is a lightweight job so 1.4.1 could follow soon after if there is a case for it..

**Comment by TeranIvy** [comment]
Ok, please let me know when fparser 0.0.4 and PSyclone 1.4 releases are ready (separately or not) so I can configure all for LFRic.

**Comment by arporter** [comment]
fparser 0.0.4 is released Iva so you can install it now. The only reason we have to update PSyclone is that we specify what (minimum) version of fparser to use. If we drop that detail from the docs then we don't have to change PSyclone.

**Comment by arporter** [comment]
Thinking about it a bit more, Rupert is correct when he says PSyclone works just fine with 0.0.2. However, the bug in fparser looks like PSyclone's problem because it causes it to generate incorrect Fortran in the Algorithm layer if `class(my_class)` is used anywhere.

**Comment by rupertford** [comment]
I agree that we have an issue with people thinking that there is something wrong with PSyclone when it is a problem with the parser and we want to avoid that where possible, but I think it would be better to give a minimum version of fparser in the documentation (that PSyclone tests would fail on if an earlier version were used) and then to say that we recommend using the latest version of fparser and that, unless stated otherwise, all versions of fparser are tested with PSyclone. Once PSyclone and fparser are used in a standard way at the Met Office we can make releases independently (or together if needed).

Of course, if we include PSyclone tests for multi-grid that include the generation of classes in the PSy-layer then at that point our minimum version of fparser should then be increased appropriately. Adding in building of tests (see issue #32) would help pick up errors here.

**Comment by rupertford** [comment]
Andy I agreed to update the documentation to suggest using the latest version of fparser but to keep the minimum supported version as 0.0.2. I have done that and merged to master (without review but pre-agreed with Andy as the it is only a small change to the documentation).
