### ISSUE TITLE
Make nemo more configurable

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#386]
Atm the mapping of loop variables to dimensions (longitude, ...) and other loop related values is hard-coded in nemo (see VALID_LOOP_TYPES, NEMO_LOOP_TYPE_MAPPING, NEMO_INDEX_ORDER). I (aka Mr Config) am moving those definitions into the config file (so other loop variables can be easily used, e.g. for my ROMS work). I imagine something like:
```
mapping-lon     = var: ji, start: 1, stop: jpi
...
mapping-tracers = var: jt, start: 1, stop:
```
Assuming that the config class in python allows the same key (mapping-tracer) to be used more than once. Or maybe the other way round:
```
mapping-ji = type: lon, start: 1, stop: jpi
```
The syntax above allows us to reuse existing functions, and the order of the keys would define the loop order (NEMO_INDEX_ORDERING).

Suggestions welcome :)

**Comment by arporter** [comment]
Sounds good. (Although I think you should be "Dr Config.") I think the default data layout should be a separate entry in the config file rather than inferring it from the order of the keys. Apart from that, should we stick with the language of ESMs ("latitude", "longitude" etc.) or generalise ("x", "y" etc.)? Since we're (very) Domain Specific here I think I favour keeping the current nomenclature but I thought it was worth raising.
