### ISSUE TITLE
Check the initialisation of pointers in generated code

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#4]
At the moment PSyclone initializes pointers using `=> null` in the PSy layer. However, this will only set the pointers to null the first time the routine is called. There was some talk about adding `=> null` makes the variable have the saved attribute, however I'd like to verify that.

Anyway, there may be cases where we want to variable to be null and it is not due to the parent routine being called more than once. If this is the case then we might want to replace `=> null` with `nullify(var)`

**Comment by MatthewHambley** [comment]
I think there are two issues at play here.

1. Declaring pointers null (the `=>null()` syntax) prevents undefined behaviour.
2. `Nullify` allows pointers to be explicitly set to null.

Thus the one is a matter of code safety while the other is a matter of correct behaviour.

It has been suggested there may be issues surrounding OpenMP but we await clarification.

What I'm saying is: hold off any changes until we understand what the problem is.

**Comment by rupertford** [comment]
OK, thanks Matthew. In general I am less worried about setting pointers to null in PSyclone as we typically know we initialize them as the declaration and the initialization are usually generated very close to eachother. However, for safety and in case people take the generated code and modify it, it would make sense to play safe as long as there is no performance implication.

**Comment by rupertford** [comment]
This has not come up as an issue from the Met Office so am closing the issue. We can open it again if required.
