### ISSUE TITLE
Profiling the CPU bits of an OpenACC application

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#425]
In my work on NEMO I'm at the stage of trying to identify the bits of code that are left running on the CPU. This isn't trivial because it's a large code base and we have of course automated the addition of the OpenACC directives. Although the NVIDIA visual profiler produces nice timelines, it can't tell you much about what's going on on the CPU. The NVIDIA solution to this is to add explicit profiling calls to your CPU code, e.g. https://devblogs.nvidia.com/customize-cuda-fortran-profiling-nvtx/

It would make my life a lot easier if we supported this in PSyclone. That way I could automatically add such profile regions to any (significant?) sections of a Schedule to which we failed to add any OpenACC.

I vaguely remember @hiker saying he'd tried using profiling with the NEMO API and nothing worked because we manipulate the fparser2 parse tree rather than creating Fortran from scratch.
The question therefore seems to be, do we wait for the PSyIR and Fortran backend to be capable of re-generating NEMO code or do we add profiling support into the current manipulation of the fparser2 parse tree?

**Comment by rupertford** [comment]
I think that in an ideal world it would be better to go the PSyIR and Fortran back-end route. Given this, what I would suggest is that we see how close the PSyIR and Fortran back-end are to supporting NEMO which will give us an estimate on how much effort it would take to get things working. If that is going to take too long I suspect it would not be too difficult to add an update method for a profile node, as you've already done this sort of thing for OpenMP and OpenACC.

**Comment by hiker** [comment]
Yes indeed, we are using update() (iirc) to modify the parser tree, which the profiling library does not support. I would also prefer to go the PSyIR Fortran backend way - since hopefully this would also solve some issues I had with ROMS which required a rewriting of the source code.

But considering your potential time constraints:
1) since NEMO is not using small kernel functions, you should be able to use any existing profiling library to get an idea about the most expensive function. Tau, score-p both use compiler wrapper, i.e. they will instrument any functions for you (though I don't know how they will interact with openacc sections - googling indicates that tau might have openacc support). You could also look at the GPTL (https://jmrosinski.github.io/GPTL/) as oakridge is doing. It relies on compiler instrumentation of functions (though a caveat: I can't get the compiler instrumentation to work on my desktop atm).
2) If this does not help, it shouldn't be too much work to add an update() implementation to the profiling interface - let me know.

**Comment by rupertford** [comment]
PR #458 has been merged to master so closing this issue.
