### ISSUE TITLE
Fortran back end with nemo api should output program/subroutine and declarations

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#430]
At the moment the psyir fortran back end only outputs nemo executable statements but needs to also output the declarations and parent program/subroutine structure.

**Comment by arporter** [comment]
Currently the generic fparser2 frontend creates a `Container` which contains one or more `KernelSchedule` objects. We now need to generalise this and introduce a `Routine` node which will be used to represent any routines found in the code.

**Comment by arporter** [comment]
In Fortran, a routine can be a Program, a Subroutine or a Function. The only difference between the last two is that a Function has a return value. Obviously, in C all subroutines have a return value and a 'program' is just another routine called `main()`. I therefore think we need to capture the name of a routine, whether it returns anything and whether or not it is the entry-point (`main` in C, a Program in Fortran).

**Comment by arporter** [comment]
I've realised that (yet again) I need to take a step back in order to take a step forwards. In this case I need to add a Routine node and that means changing the class hierarchy. I'll do this in #896.

**Comment by arporter** [comment]
Currently, in the NEMO API, an Invoke has a NemoInvokeSchedule. Giving this to the Fortran backend always produces code that defines "subroutine name(...)". I don't know where "name" comes from and, for nemo/eg1, it should be "program tra_adv" anyway.
As things stand in the NEMO API, each routine is represented by an `Invoke` since it is taken to be a manually-written PSy layer.
Possibly, each `Invoke` should have an associated `Container`. In PSyKAl APIs, this Container will represent the Fortran module containing the definition of the PSy-layer routine. In the NEMO API, it could represent either a Program or a Module. If the latter, several `Invoke`s could share a single `Container` if they were all routines in the same Fortran module. In fact, that suggests that the `Container` should be associated with the `Invokes` object, rather than each `Invoke`.

**Comment by arporter** [comment]
@sergisiso and @rupertford - do we have a plan yet for how a `Container` relates to `Invoke` and `Invokes` in the LFRic and GOcean APIs? Looking at what Sergi's done recently in gocean/eg8, I can see that he has a `Container` in the `PSy` object and that's what he gives to the backend.

**Comment by rupertford** [comment]
I've not thought about what the PSy-layer classes should look like long term. I guess it would keep things simpler if we could avoid changing the PSy->Invokes->Invoke->Schedule hierarchy and how they are called as that is what all of our scripts are based on - but perhaps that should be up for grabs. However `PSy` and `Invokes` are not Node's. I guess if `Invoke` is thought of as *being* an `InvokeSubroutine` and PSy is thought of as *being* or *having* a PSyContainer (module) depending on what is simplest and `Invokes` is just a convenience class then would that would work for LFRic, GOcean and most of NEMO? If there is no Container i.e. just a subroutine or a program then we would either have to manage where the reader visitor started from or create a DummyContainer, which does nothing.

**Comment by arporter** [comment]
Yes, I think that would work. I just need to look and see how easy it is to create a Container for the NEMO PSy object.

**Comment by arporter** [comment]
I've brought this branch up-to-date with master and am working through the failing tests. I've attempted to replace the existing code in NemoInvokes with the new `generate_psyir` but it just gives a CodeBlock for a `Program`. @sergisiso and @rupertford, is there a plan to improve on this?

**Comment by rupertford** [comment]
If you need it I can add it in. I didn't add it in previously as I was not sure we had agreed on how to represent a program in the PSyIR.
