### ISSUE TITLE
Handling of scalar grid properties in OpenCL

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#459]
If a scalar grid property (say `go_grid_dx_const`) is used in opencl, the created code can not be compiled since it will contain a reference to `dx_device`.

**Comment by sergisiso** [comment]
This issue is triggered by the commented:
`assert GOcean1p0OpenCLBuild(kernel_outputdir).code_compiles(psy)`
on the src/psyclone/tests/gocean1p0_opencl_test.py::test_set_kern_float_arg unit test.

The problem is that the PSy layer generates a `$name_device` for each `GOKernelGridArgument` (src/psyclone/gocean1p0.py:1062) but some of them are arrays and have device_ptr allocated and others are integers and not.

Given that the OpenCL kernel already expects integers to be passed by value, see signature of the associated kernel generated:
```
__kernel void bc_ssh_code(
  double rtime,
  __global double * restrict ssha,
  int max_x_index,
  __global int * restrict tmask
  ){
```
an easy fix is to look at the GRID_PROPERTY_DICT and do not add the `_device` suffix to grid_properties that are integers. I will open a PR for this.
