### ISSUE TITLE
Coded version.py rather than a generated one

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#53]
At the moment we generated a version.py file after we have run setup.py. This then acts as a central place for documentation etc to pull the correct version.

I would prefer there to be a pre-existing version.py file which is read by setup.py as well as other parts of the distribution as we would then not need to run setup.py before anything else. This issue is observed when trying to build the documentation.

Andy has pointed out that there is a bit of chicken and egg here as setup.py will not be able to see version.py until the distribution is installed, which is done by setup.py.

However, he also said that you could play with the python path within setup.py to point to the correct place (the relative location is known). I would prefer to do this.

**Comment by arporter** [comment]
I had a bit of a look around at how best to do this. This page summarises the options:

https://packaging.python.org/guides/single-sourcing-package-version/

I've gone for a Python version.py module file (means we don't have to worry about parsing/regex) but, in order to avoid having to have psyclone installed, I read that file using execfile() in both conf.py and setup.py.

**Comment by arporter** [comment]
Just need to do pep8/pylint on the three modified files now...

**Comment by rupertford** [comment]
pr #88 is now on master so closing this issue
