### ISSUE TITLE
Documentation for Using OpenSUSE

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#55]
I've started to document the installation process on OpenSUSE, which has a few issues (e.g. the default pip only installs for python3). The current state is in: https://github.com/hiker/PSyclone/blob/opensuse-doc/doc/system_specific_setup.rst

My main suggestion which needs some discussion:
quite a few packages that are in the current docs installed using apt-get can be installed using pip. The advantage is that there is then more in common, and imho a bit of a restructuring might be useful in order to reduce duplicated documentation (and therefore reduce work if things are changed). My proposed (not yet done in my branch) structure would be:

1. User Installation
    - Ubuntu specific (apt-get) installations - mostly pip I think
    - OpenSUSUE specific (zypper) installations (pip again)
    - Common (pip) installation
        - Including details about --user and how to uninstall
2. Developer installation
    - Ubuntu specific (apt-get) installations (latex)
    - OpenSUSE specific (zypper) installations (latex)
    - Common (pip) installation (no more --user and uninstall instructions)

Am happy to follow any other approach, e.g.:
1. Distro specific installation
    - Ubuntu
        - User
        - Dev
    - OpenSUSE
        - User
        - Dev
2. User (pip-based) installation, common to all distros
    - including --user and how to uninstall
3. Developer (pip-based) installation, common to all distros

Or we can leave it the way it is, but I would say that this means that around 90% of the content is identical between the distros (just apt-get vs zipper, a few package names are different).

And could you let me know when is a good time to do this? It appears that you are currently working on the way it is installed and the docs, so let me know when you are finished before I start on it.

Feedback welcome!

**Comment by rupertford** [comment]
The proposed restructuring assumes that the distribution-specific installation can be done first and the general installation follows. That seems to be the case so I agree that it is an improvement and makes sense to do now that we have information for more than one distribution

I think both proposed structures are good but I prefer the first one as it has the user/developer split higher level than distribution split and I think most people will be users.

Please go ahead with the changes if you're happy to do so. We will only be updating the documentation just before we make a new release and there is no schedule for a new release at the moment - we tend to make new releases when new features are requested by users or bugs have been found. Also, the changes will be relatively minor - just an update of how to install due to PSyclone being installable via pip.

Note that people who install LFRic tend to do so on supercomputers which means that PSyclone needs to be installed there too and our feedback so far is that pip is not available. A non-pip installation might therefore be beneficial at some point (although I think the Met Office maintain their own installation instructions) but that is separate to this issue.

**Comment by hiker** [comment]
OK, will do. I am also fixing the latex size issue, from 1600 packages down to ~140 and ~300MB disk space requirement.

**Comment by rupertford** [comment]
A reduction in the size of the required latex distribution would be great, thanks for looking at this. Note, from our email discussions I am aware you had size issues on a standard VM installation so this change could avoid this problem for others as well.

**Comment by hiker** [comment]
I have a first prototype ready. I'll need to do some proofreading, but it would be great if you could have a very quick look to see if you are happy with the 'refactoring':
https://github.com/hiker/PSyclone/tree/opensuse-doc

Note that there is a lot of duplicated documentation now between getting_going and system_specific_setup files (installing fparser, pyparsing, graphviz; then at least using py.test).

I would actually recommend to move the 'how to make the html, pdf, run pylint, ...' instructions all into the getting going section and removing it from the system specific setup. And similarly remove the pip installation instructions from the getting going section, leaving this in the system-specific setup. And then maybe rename the system-specific-setup to be just: installation  (?)

**Comment by rupertford** [comment]
The refactoring looks good thanks. I'll hold off commenting on minor issues until the review.

I take your point about replication. Originally the idea was to have general information about installation, with pointers on how to get the appropriate software and pointers to remote documentation, and then have separate specific installation sections which tell you exactly what to do. However, the general information and the specific information is very similar, as you say. Therefore I think you are right that things could be refactored. I suggest further refactoring is added as a separate issue and we get this one onto master, rather than adding more to this one.

**Comment by arporter** [comment]
PR #66 has been merged. Closing issue.
