### ISSUE TITLE
Schedules having SymbolTables

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#554]
Currently only KernelSchedules have a SymbolTable. However, I now need to extend the NemoInvokeSchedule so that it too has one. On reflection, I suspect we should add it to the InvokeSchedule base class (which is implied by #312). To avoid duplication we should then have KernelSchedule and InvokeSchedule inherit from a common base class that has a SymbolTable. However, we probably don't want *every* Schedule to have one (e.g. those containing the sequence of statements within an if-body) which means we need to re-jig our Schedule hierarchy. Does anyone have any thoughts/naming preferences for what we call a Schedule that has a SymbolTable?

**Comment by hiker** [comment]
Why shouldn't each Schedule a SymbolTable? In C++ you can easily declare variables within an if-body:
```
if(a)
{
   use_outer_scope(b);    ! This uses 'b' from the outer scope
   float b = 1/a;
...
}
```
I would consider a Schedule to be a block enclosed in {} in C (technically even that is not flexible enough, see the `use_outer_scope(b)` call in the example above, but since we don't have to parse C, I think that's fine).

Now this is then obviously a problem in Fortran (if we declare a different `b` in the outer scrpe), but we have that problem anyway (and ignore it, since we parse only Fortran). And since the decision was to support local declarations, I think it's easiest to have it for each schedule.

**Comment by rupertford** [comment]
I agree with @hiker and this is something that @sergisiso and I have discussed in the past. The particular case was something like the following ...
```
subroutine x
real :: tmp
do ... end do
do tmp=rhs; lhs=tmp; end do
do ... end do
end subroutine x
```
Fortran will add the ```tmp``` variable to the symbol table associated with the subroutine's schedule. However, the scope of ```tmp``` is actually within the schedule associated with the second loop. I think it should be valid to specify the scope there (or further out). We can then have transformations which can move variable declarations around. We could also support a hierarchy of scopes in the Fortran backend, or simply require appropriate transformations beforehand.

**Comment by TeranIvy** [comment]
Technically, an InvokeSchedule creates a Fortran subroutine so I think it is natural for it to have a SymbolTable.  Another big reason for supporting this from my side is it would help me significantly in Kernel/Node extraction, for both a) dumping the variables from an Invoke and b) declaring them in a self-contained ProgramUnit.

**Comment by arporter** [comment]
OK, I shall move the SymbolTable from KernelSchedule to Schedule (as part of #500).
