### ISSUE TITLE
fparser2 frontend does not support the ALLOCATABLE attribute

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#594]
A declaration like the following:

    real, allocatable, dimension(:,:,:) :: umask

causes:

    NotImplementedError: Could not process (Intrinsic_Type_Spec('REAL', None), Attr_Spec_List(',' (Attr_Spec('ALLOCATABLE'),)), Entity_Decl_List(',', (Entity_Decl(Name('umask'), Assumed_Shape_Spec_List(',', (Assumed_Shape_Spec(None, None), Assumed_Shape_Spec(None, None), Assumed_Shape_Spec(None, None))), None, None),))). Unrecognized attribute 'ALLOCATABLE'.

**Comment by arporter** [comment]
I'm not sure how to capture this information in a language-independent way. In Fortran a dummy argument may be given this attribute - it does not necessarily imply that the variable must be allocated in the subsequent code, just that it has been (or will be) allocated at some point. In C the equivalent would be a pointer declaration along with some associated information on the extent of the associated buffer. Essentially it is marking an Array as being dynamic rather than static so maybe it's a matter of letting `Symbol`s that represent Arrays have an `is_dynamic` property?

**Comment by arporter** [comment]
Bringing in @sergisiso as he has a less Fortran-biased view of the world :-)

**Comment by rupertford** [comment]
From the symbols point of view, isn't it that the specification of the size(s) has been deferred? I'm not sure about using dynamic as I would say that `real :: a(n)` is dynamic if `n` is a variable rather than a parameter/constant. Are we going to include concepts for allocate/malloc and deallocate/free and have a policy on what happens if a variable goes out of scope? Or should that remain within a CodeBlock? For the record I quite like create and destroy as it is similar to class/instance.

**Comment by arporter** [comment]
I agree about 'dynamic' not being a good fit. We could go for deferred-size but would also need an attribute to capture that a symbol had the 'allocatable' attribute as we'll need to know that when re-creating Fortran code.

**Comment by arporter** [comment]
![20191121_111346](https://user-images.githubusercontent.com/17409212/69343272-2e863900-0c65-11ea-988a-99543c43d137.jpg)

At the moment, the `shape` property of a `Symbol` is a list that may contain either Literals, Symbols or "deferred". Following on from the above image, "deferred" would become "internal" (meaning that the dimension has a defined extent and the run-time system knows what it is). We would then have deferred to mean that the extent really is unknown (potentially not yet defined if the array has not been allocated yet.)

**Comment by sergisiso** [comment]
I am happy with this although I don't like the 'internal' name too much, would simply 'runtime' extent be better?

> Bringing in @sergisiso as he has a less Fortran-biased view of the world :-)

For the time being I think it is OK to have a restrictive C/OpenCL backend that when it finds something that does not fit the back-end it just breaks. As far as we can parse nemolite2d is good for now.

In the long term I think the C/C++ backend should use some of the C++ array/span representation that are similar to Fortran arrays instead of raw C pointers, and these containers have the ability to specify 'dynamic' extents or being not allocated yet, so it is not an issue to add these concepts on the PSyIR.

**Comment by rupertford** [comment]
It's my fault it's called "internal". @arporter also suggested "runtime" when we discussed it. My issue with this is that - to me - this implies the sizes are not known until runtime. However, that is also the case for "symbol", if the symbol is a variable (these are called automatic arrays in Fortran). I think the defining feature here is that the sizes of the array are carried with the array object/structure internally as attributes. Ignoring the actual name for the moment, do you disagree with this logic? On the assumption you agree then whilst we came up with the name "internal", it could be another name e.g. attribute?

**Comment by arporter** [comment]
I quite like "attribute" and would really like to get on with this Issue as it's blocking my NEMO work. Are we in agreement?

**Comment by arporter** [comment]
Currently the `shape` property of a Symbol is a list that contains  a `None` for each dimension with an unknown extent. This is subsequently used to infer that the extent is 'deferred'. However, we now need to differentiate between the cases where the unknown extent is 'deferred' (for an allocatable array) or 'attribute' (for any other type of array).
