### ISSUE TITLE
Use Symbol Table to rename symbols

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#703]
At this stage there is a restriction that e.g. a PSyData module cannot be used if the user application uses a module with the same name (at least in NEMO) and an exception is raised. I don't think we can actually do anything if a module with the same name is used, but the real problems seems to be that the symbol imported (PSyDataType) might be already used.

Use a namespace manager (or SymbolTable?) to potentially rename the PSyDataType if it already exists.

**Comment by arporter** [comment]
I think we also need to add the relevant names to the list of 'reserved names' in the namespace manager. That way, if a (peverse) user supplies a variable called e.g. 'psy_data' from the algorithm layer we will avoid clashes when constructing the psy-layer code.

**Comment by sergisiso** [comment]
I took the liberty to rename this issue as the NameSpace Manager doesn't exist anymore. And I am going to address this soon as the Kernel Fusing will need this for potential name clashes bewtween kernels.

**Comment by sergisiso** [comment]
@arporter @rupertford @hiker I actually need some opinions about the interface:

`symbol.rename(str)` or `symbol.name =` would currently not work because we need to update the 'key' in the symbol table that contains the symbol. (Or would every symbol have a link to its belonging symbol table be appropriate? I prefer not  )

So it should be:
`symbol_table.rename(<from>, <to>)`
but
- Should `<from>` be a symbol or a str "name" that is looked up in the SymbolTable? I see pros and cons in both.
- Should `<to>` be a exact match that fails if the name can't be used, or a root_name that follows the available symbol naming rules to get a name?

**Comment by arporter** [comment]
My gut feeling is that <from> should be a Symbol but maybe we should support both options. I would have thought that it would be most useful for `<to>` to be a root name as otherwise we will have to separately generate a unique name for the symbol. Perhaps the call should return the new name?

**Comment by rupertford** [comment]
I think symbol as well and I think the method name should be `rename_symbol`, otherwise it sounds like we are trying to rename the symbol table.

I would go for an exact match as I think that will be the main (only?) use in practice (although I already fell the examples where I am wrong being typed).

**Comment by sergisiso** [comment]
Good point about "rename_symbol", there is also agreement that `from` should be a symbol.

>I would go for an exact match as I think that will be the main (only?) use in practice(although I already feel the examples where I am wrong being typed).

All my cases don't need exact match :) I need it for resolving name clashes in transformations but I don't really care what the new name is: "name_{1,2,3}" is fine for me.

**Comment by sergisiso** [comment]
But then.. what if one needs exact match, with this API the user will have to manually compare that the result is as expected.

While if we only accept exact match it would be calling:
 `symbol_table.rename_symbol(from, symbol_table.next_available_name(from.name))`
for non-exact cases which is verbose but quite readable.

I may go for only exact match for now and let the reviewer have the last word.

**Comment by arporter** [comment]
Sounds good Sergi.
