### ISSUE TITLE
[LFRic] PSy-layer intents should almost always be (in) not (inout)

### ISSUE THREAD

**Issue by stevemullerworth** [stfc/PSyclone#712]
Can field (and where appropriate, other) intents be changed to (in) in the PSy-layer?

Currently, PSyclone declares the intent of a GH_WRITE or GH_INC field as being (inout). The fact the field data is being modified does not mean the field is being modified, so such fields can be declared as (in).

LFRic would prefer to mandate that all fields (and field collections) in algorithms are declared as intent(in) so as to be correctly aligned with the reality that field objects themselves are not modified. The PSyclone change is a prerequisite for this as one cannot pass an intent(in) variable into a routine where it is declared intent(inout).

**Comment by TeranIvy** [comment]
The related LFRic design discussion ticket is [2097](https://code.metoffice.gov.uk/trac/lfric/ticket/2097).

**Comment by rupertford** [comment]
Hi @stevemullerworth.

We could certainly do this (although it does not seem to make sense to me!). However, before doing so could you confirm that the resultant code works with all the compilers we would like to run on (or at least can run on :-)) at high optimisation. The reason I raise this is because we purposely make use of inout to ensure that the contents of a data object are not lost. I don't remember the details but we used to have problems which we fixed by using inout.

**Comment by arporter** [comment]
I've read the ticket (2097) and the Red Fortran book and understand (Field objects contain *pointers* to data - the data isn't actually part of the Field object). I suspect it's a fairly simple change for us to make but might involve a lot of leg work. What kind of priority does this have?

**Comment by stevemullerworth** [comment]
Not urgent, but it would be nice to have it in the schedule in the next 6 months say? The reason is that when it goes in we will change all the intents in LFRic code to (in) and change our coding standards to match, so it would be good to do it before we have too many more developers.
