### ISSUE TITLE
[PSyIR-FE] fparser2 frontend does not support the PUBLIC attribute

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#732]
Attempting to process the NEMO source with the version of PSyclone associated with #596 (addition of symbol-table support) reveals that the Fortran frontend does not yet support the PUBLIC attribute.

**Comment by arporter** [comment]
This is going to be involved as the symbol table does not currently have the concept of private/public.

**Comment by arporter** [comment]
Since the `SymbolTable` just contains a list of `Symbol` objects, whether or not a symbol is private is then a property of the `Symbol` object. I think it should in fact be a property of the base `Symbol` class. What do @sergisiso and @rupertford think?

**Comment by sergisiso** [comment]
@arporter But isn't `PUBLIC` the default visibility in a Fortran module? So if Nemo just have `PUBLIC` attributes it would still work by ignoring them, right? (or adding a hint for the back-end to put it back but it doesn't change what it represents)

The issue is if there is `PRIVATE` attributes, which we may need to do something different.

**Comment by arporter** [comment]
Yes, NEMO is declaring that everything in this particular module is private by default and then explicitly marking some attributes as public.

**Comment by sergisiso** [comment]
PR #735 adds support for Fortran PUBLIC and PRIVATE attributes. Closing this issue.
