### ISSUE TITLE
[PSyIR-FE] Capture symbol names for routines

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#736]
When parsing Fortran code we currently do not attempt to capture routine names as symbols. In #732 we're extending the FE to cope with access statements (PUBLIC/PRIVATE [xxx, ...]) and I was hoping to be able to validate that we knew (or could know) about the source of `xxx` etc. However, if `xxx` is a subroutine name (and if often is) then we don't yet know about it. In this case we just add a basic `Symbol` to the symbol table.

**Comment by arporter** [comment]
@sergisiso has also pointed out that in capturing symbols for routines, we will also have to extend the Interface concept (that currently only applies to DataSymbols).

**Comment by sergisiso** [comment]
The Interfaces are now general to all Symbols and a RoutineSymbol has been added in #787 but this issue is still open as the front-end has not been changed to capture any new symbol and I believe the routines are just captured when the symbol is first found without context and is just set as Symbol for now.
