### ISSUE TITLE
[PSyIR] Add a Call node

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#786]
We would like to be able to create and reason about calls in the PSyIR so need a node to capture this concept.

**Comment by rupertford** [comment]
Created branch 768_psyir_call_node

**Comment by rupertford** [comment]
I've concentrated on a call for the moment, i.e. something that is a statement. It's less clear to me how we would support functions as we already have operators with similar properties (and would we support functions that return more than one thing?). So that is for another issue.

To support a call I've added a RoutineSymbol - which stores the name of a routine. This should also support the naming of routines inside containers, but at the moment we use a Kernel to specify a schedule that can be called (a routine) which I don't think we want as it is a DSL concept, so I suggest we need to add another Node to the PSyIR that subclasses a Schedule and call it something like EntryPoint. An EntryPoint would therefore be a Schedule that can be called from somewhere else. Anyway, that would also be another issue.

**Comment by rupertford** [comment]
I can now generate Fortran use statements and calls but have taken the minimal path to get this working so there is a lot of restructuring to do. In particular 1) the (Data)SymbolInterface code needs to be properly shared between DataSymbol and RoutineSymbol. 2) The code for pulling out global arguments in the SymbolTable needs updating as it assumes that it should only look at DataSymbol objects.

However, I think it is probably worth @sergisiso taking a look at the general approach (RoutineSymbol + Call) before I continue.

**Comment by sergisiso** [comment]
I gave a glance at the implementation and the general direction looks good. As you say is better to concentrate into subroutines first but when we do functions Fortran and C both return both only one value (which can be an aggregated type) but then the call is an expression rather than a Statement (not sure how to best do this yet).

Also agree with the "EntryPoint" although I would call it something more common, like Subroutine/procedure, and it is mostly implemented already in kernelSchedule it just needs to be stripped and maybe then kernelSchedule inherits from it. The new thing is that maybe we can now type check the list of arguments.

Regarding 1) , the generalizing Interfaces has already come up before, I think is a good idea. I am not sure what you mean in 2).

One bit which doesn't seem right is that you check all arguments are References, while it should be enough if they are expressions e.g. `call routine(3+4)`.

**Comment by sergisiso** [comment]
A PSyIR Call node and a RoutineSymbol have been added. Closing this issue.
