### ISSUE TITLE
make the wtheta and w2v function spaces discontinuous

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#84]
At the moment wtheta and w2v are (horizontally) continuous function spaces in PSyclone. These should be changed to discontinuous. This was originally ticket [829](https://code.metoffice.gov.uk/trac/lfric/ticket/829) on the Met Office LFRic trac on SRS.

**Comment by TeranIvy** [comment]
Hi @rupertford, I will introduce this change in #25 (readwrite access for discontinuous quantities) as agreed with the Met Office people. Another change could be grouping `any_w2` with `VALID_ANY_SPACE_NAMES` as it essentially behaves like any space (unspecified continuity).

**Comment by TeranIvy** [comment]
In #25 I ran the tests with 
```
DISCONTINUOUS_FUNCTION_SPACES = ["w3", "wtheta", "w2v"]
CONTINUOUS_FUNCTION_SPACES = ["w0", "w1", "w2", "w2h", "any_w2"]
```
and it reported failures in `dynamo0p3_tests.py` for 2 tests, `test_field_fs()` and `test_dynloop_load_unexpected_func_space()`. The latter one is easily modified as the order of metadata in `VALID_FUNCTION_SPACES` will be slightly different after the change.

The `test_dynloop_load_unexpected_func_space()` fails because a continuous writer (`f3` on `wtheta` space) is changed into discontinuous one. Instead of 
```
      CALL f1_proxy%set_dirty()
      CALL f3_proxy%set_dirty()
```
the generated code is now
```
      CALL f1_proxy%set_dirty()
      CALL f3_proxy%set_dirty()
      CALL f3_proxy%set_clean(1)
```
I checked this behaviour for only `w3` discontinuous and an original discontinuous reader `m3` changed to writer (metadata defined in `testkern_fs.F90` which should really be called `testkern_fs_mod.F90`). The test again fails with expected differences in generated code:
```
      CALL f1_proxy%set_dirty()
      CALL m2_proxy%set_dirty()
      CALL f3_proxy%set_dirty()
      CALL m2_proxy%set_clean(1)
```
There are transformation tests with continuous readers & discontinuous writers after applying redundant computation. I am not sure about tests for continuous readers & discontinuous writers without redundant computation. I guess discontinuous `wtheta` would make `test_field_fs()` one such test (perhaps more would be needed).

This change is no yet committed in #25 and I will leave it for after all READWRITE functionality and tests are introduced.

**Comment by rupertford** [comment]
Hi @TeranIvy. Where are you up to with discontinuous wtheta and w2v? Is this in hand? If so I'll look at something else :-) The reason I ask is that it is something that would benefit Tom, as mentioned (indirectly) in #127.

**Comment by TeranIvy** [comment]
Hi @rupertford. It wasn't clear to me whether you wanted to work on this or not so I started introducing discontinuous wtheta  and w2v in #25. I can simply copy changes to wtheta and w2v I made in #25 here (source and tests) and send it for review in a couple of days. Would that work?

**Comment by rupertford** [comment]
Thanks for the update and suggested solution @TeranIvy. If it's not too much work on your part to separate out these changes into another branch and create a subsequent pull request then I think your suggestion is a good one.

**Comment by TeranIvy** [comment]
Hi @rupertford, I have a question about new tests for wtheta and w2v. The current tests for discontinuous function spaces/fields are working with only w3 and the relevant Fortran files have w3 in their names. Should I copy and run each of these tests for both wtheta and w2v as well?  Alternatively, I can add randomly apportion w2v or wtheta to a new instance for each of these tests. I think it would be good to extend each of them to check for at least one more discontinuous space.

**Comment by rupertford** [comment]
Hi @TeranIvy. I agree that a mixture of 2 and 3 works, choosing one or the other depending on the nature of the test. Obviously if there were any code specific to w3, wtheta or w2v then that would need to have its own test but I suspect there are no examples of this.

**Comment by rupertford** [comment]
pull request #128 now on master. Closing issue
