### ISSUE TITLE
Support for include files

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#92]
I noticed that Fortran include statements are discarded when creating the alg layer. While in my case I could use a simple work around (replace "include netcdf.inc" with "use netcdf4.f03"), this is not always feasible, e.g. udunits and cdo do not provide .mod files.

There was a lengthy discussion about this, I'll leave it to the individual people to copy&paste their opinion.

For my case I don't need the include files to be parsed, just leaving the Fortran include statement in the generated files would be good enough.

**Comment by arporter** [comment]
fparser does, in theory (i.e. I can see code related to this), support INCLUDE statements and tries to do the right thing by recursively parsing them too. Since one can use INCLUDE at almost any point in a piece of Fortran it has to do this otherwise there's no guarantee it can successfully parse such a file.
I think we have two options therefore:
 1. Extend PSyclone to make proper use of this functionality and generate Alg files with all includes put in
 2. Extend PSyclone and fparser to disable this functionality and leave INCLUDE statements as is, with the risk that the parser will fail.

**Comment by rupertford** [comment]
I think there are other options:

3. abort if an INCLUDE statement is found in the code
4. abort if an INCLUDE statement is found within executable statements but leave it as-is if the include statement is not.

I think only 1. or 3. are realistic options as the parser could fail in random ways otherwise. My preference would be for 3 immediately as we do not support them at the moment and 1. if it is not too difficult to get this functionality working robustly. 

I presume we are only talking about fparser1 here and not fparser2.

**Comment by arporter** [comment]
The code that (purports to) handle INCLUDE statements is in the `FortranReader` and therefore I think it is common to both fparser1 and fparser2. I agree with your summary. We could probably add an option to `FortranReader` for "abort if an INCLUDE is encountered."

**Comment by arporter** [comment]
I've come back to this as it is an issue in NEMOVAR as well as NEMO since they both include mpi header files. fparser was failing to parse those headers because it contained functionality that took notice of Python-style encoding information and it happens that the headers have that. fparser has now been extended so that this functionality is disabled by default (since it is not part of the Fortran standard) and now MPI headers can be parsed. When an `include` is found and parsed successfully, the parse tree will not contain an `include`. Therefore, we should now extend PSyclone to check for any `include` nodes and abort if they are found.
